### ISSUE TITLE
Example code returning NoSuchMethodError 

### ISSUE THREAD

**Issue by mushthak** [Earlybyte/aad_oauth#1]
My scope is "openid Calendars.ReadWrite User.Read email"

In login page, am getting this error when I enter my outlook email and click "Next" button.

<img width="241" alt="Screenshot 2019-03-24 at 8 16 49 PM" src="https://user-images.githubusercontent.com/11793859/54881091-39888f80-4e72-11e9-833b-0d2502f6f5c5.png">

**Comment by tobiasmeier78** [comment]
Hi,

thank you for submitting a bug. Currently we are working on another project and unfortunately we don't have the time it usually takes to maintain such a library.

If you want to participate on the code we are open to discuss about it.

best regards

**Comment by reuban-isc** [comment]
@mushthak This is not an issue on the plugin. Please make sure that the username you use to login is created as on object in the Azure Active Directory instance. 

For example if you had created the personal Azure instance with the email "johndoe@outlook.com" then you need to create a user in your instance Azure Active Directory as "newuser@johndoeoutlook.onmicrosoft.com". Thereafter use this new account to verify the application.
