### ISSUE TITLE
Error in back button after login

### ISSUE THREAD

**Issue by osorito** [Earlybyte/aad_oauth#10]
After your first login and you log out. If you tap on login you will see the page "Pick an account" if you press back it throws an error
<img width="460" alt="Screen Shot 2019-04-20 at 6 02 03 PM" src="https://user-images.githubusercontent.com/22304375/56462783-167ccd00-6397-11e9-8691-823785bf36a9.png">

**Comment by yugandh** [comment]
Hi @osorito,
In below code, if you remove line in catch  **showError(e);** , the alert will go away and you can just print exception instead of alert view. Print(e). Temporarily i used this approach to solve this problem and i am thinking it's the right way.
  void login() async {
    try {
      await oauth.login();
      String accessToken = await oauth.getAccessToken();
      showMessage("Logged in successfully, your access token: $accessToken");
    } catch (e) {
      showError(e);
    }
  }

**Comment by osorito** [comment]
Thanks. As instructed, the error is gone.
