### ISSUE TITLE
login / registration with native components instead of WebView

### ISSUE THREAD

**Issue by qbait** [Earlybyte/aad_oauth#100]
Is it possible to use Azure B2C auth and have smooth native authorization instead of WebView?

**Comment by jacojvv-dev** [comment]
Hi @qbait - as far as I know there isn't any way to do it as Azure B2C relies entirely on redirecting to the browser for logins.

If you need this sort of functionality you could look at Firebase authentication as an option. The pricing is about the same and it allows you to fully control the user interface with custom flutter widgets.

There are others available (AWS Cognito, Auth0, etc...) - but I have no experience with them and cannot comment on their use cases.

**Comment by qbait** [comment]
Thanks @jacojvv-dev !
