### ISSUE TITLE
Calling getAccessToken directly no longer ensures the retrieval of the token

### ISSUE THREAD

**Issue by jacojvv-dev** [Earlybyte/aad_oauth#101]
From the readme "You can also call getAccessToken() directly. It will automatically login and retrieve an access token." but this does not seem to be the behavior as of version 2.1.0.

I did read the code and I can't see any place where getAccessToken branches of to logging in, as far as I can tell it will just return null. Was this an intended behavior change or is this a bug?

For now I have mitigated the issue by downgrading back to 2.0.0 until I can be sure that the login is also performed when getAccessToken is called.

**Comment by sladomic** [comment]
Hi @jacojvv-dev you're right. The
