### ISSUE TITLE
Invalid Access Token

### ISSUE THREAD

**Issue by manjotsidhu** [Earlybyte/aad_oauth#102]
I was working on fetching profile details using Microsoft Graph API but it turns out the JWT access token is invalid.
I am using this code -
```
await _oauth.login();
_accessToken = await _oauth.getAccessToken();
```

Checking the token in https://jwt.ms/ shows invalid token and calling Graph API on `/v1.0/me` says -
```
"code": "InvalidAuthenticationToken",
"message": "CompactToken parsing failed with error code: 80049217",
```

**Comment by f1dz** [comment]
Same here, I tried to parse with https://jwt.io/ and it has an error, it said ```Invalid Signature```. It seems the generated token is invalid because it doesn't include a ```dot (.)``` on it. If someone needs further info, I am happy to help.

**Comment by dsouzadyn** [comment]
Hi @f1dz can you share what you did so that it doesnt show up as invalid?

**Comment by f1dz** [comment]
> Hi @f1dz, do you know how to resolved the Invalid Signature?

I just reverted it to older version

**Comment by dsouzadyn** [comment]
Hi, I found out technically, it being an invalid signature is expected, since Microsoft tokens arent 100% jwt.

You need to check it on jwt.ms, not jwt.io
