### ISSUE TITLE
Firewall problem

### ISSUE THREAD

**Issue by osorito** [Earlybyte/aad_oauth#11]
If you are behind a firewall, after typing your email it does not send you to your organizations login page. It remain's in a white page. 
<img width="375" alt="firewall" src="https://user-images.githubusercontent.com/22304375/56523656-cb3cf880-6515-11e9-901c-ef027630af10.png">

**Comment by behlsoft** [comment]
> If you are behind a firewall, after typing your email it does not send you to your organizations login page. It remain's in a white page.
> <img alt="firewall" width="375" src="https://user-images.githubusercontent.com/22304375/56523656-cb3cf880-6515-11e9-901c-ef027630af10.png">

any way we can get success?
