### ISSUE TITLE
Update HTTP Client

### ISSUE THREAD

**Issue by manjotsidhu** [Earlybyte/aad_oauth#110]
Currently the latest version of https://pub.dev/packages/http is 0.13.3. Please update the http client as our code is restricted to use 0.12.0 due to aad_oauth.

**Comment by robertmrobo** [comment]
I desperately need this update as well. 😥

**Comment by dunatron** [comment]
Hey I would also like to use this package but every version of aad_oauth depends on http ^0.12.0 which was [last published in 2018](https://pub.dev/packages/http/versions/0.12.0). any chance of this being updated?

**Comment by nyanpasu** [comment]
+1

**Comment by nyanpasu** [comment]
https://github.com/Earlybyte/aad_oauth/pull/103 will fix this, but it also makes significant changes to aad_oauth and is still pending review.

In the meantime I have a [fork](https://github.com/nyanpasu/aad_oauth) which doesn't change behaviour and updates the http package and other packages.

**Comment by chester23491** [comment]
Hi @manjotsidhu 
We released the version 0.2.2 few days ago. The latest http package is now included.

Can you please check and close this issue?
