### ISSUE TITLE
Platform exception, the specified child already has a parent

### ISSUE THREAD

**Issue by justoke** [Earlybyte/aad_oauth#120]
I have successfully used this package to integrate Flutter app with Azure B2C AD. Occasionally I'm getting this exception and can't figure out why this occurs.

Call Stack
![image](https://user-images.githubusercontent.com/26506785/127135897-61b7f64b-bab3-4624-b280-ced0af2a825b.png)

Exception in RequestCode.requestCode on line 22:
await _webView.launch
![image](https://user-images.githubusercontent.com/26506785/127135552-60611b12-ed61-45df-af7e-488278e43bbe.png)

**Comment by OssiPesonen** [comment]
This issue is not stale. The developers seem to have abandoned the repo. Some of the stuff here doesn't seem to work out of the box. I have the same issue.

**Comment by justoke** [comment]
I still get this issue.
