### ISSUE TITLE
Get DateTime of AccessToken

### ISSUE THREAD

**Issue by fatimahalmostaneer** [Earlybyte/aad_oauth#123]
Dears, How can I get the date time of expiration of the token.

**Comment by OssiPesonen** [comment]
You can decode a JSON web token and read it's `exp` property. There's a package for JWT decoding, if you don't want to write a decoder yourself:
https://pub.dev/packages/jwt_decode

To see your access token payload, simply paste it in something like https://jwt.io/ to see it decoded.
