### ISSUE TITLE
On iOS oauth.login(refreshIfAvailable: true), always shows Azure login screen.

### ISSUE THREAD

**Issue by derekllaw** [Earlybyte/aad_oauth#131]
We have iOS and Android Apps with the same code for accessing the Azure B2C authentication. After logging in with email and password we close the app. On restarting the App on Android, the token refreshes when we call oauth.login(refreshIfAvailable: true) with no further interaction. On iOS, we must enter the email and password again.
We can see that flutter_secure_storage is used to store TOKEN between runs (and that it uses the Keychain on iOS) and have tested that we can save and restore data directly, so we cannot see what might be going wrong.

**Comment by humanolaranja** [comment]
I'm facing this issue in 0.4.1

**Comment by Core121** [comment]
Was there any solution to this?
