### ISSUE TITLE
Not getting the updated access token after 60 minutes expiry time frame

### ISSUE THREAD

**Issue by yugandh** [Earlybyte/aad_oauth#14]
Hi,

I logged in to the mobile application(iOS and Android) using email and password.
After 60 minutes time frame i opened the mobile application and click on login button, since i already given email and password  it will automatically skip web-view login.

I used below code to make a Microsoft graph api call.

try {
await oauth.login();
String accessToken = await oauth.getAccessToken();
var response = await http.get(https://graph.microsoft.com/v1.0/me/, headers: {"Authorization": "Bearer $accessToken});
print(response.body);
} catch (e) {
  print('login error');
}

I am getting access token expiry error and unable to fetch data from Graph-API.(https://graph.microsoft.com/v1.0/me/)

I have used 0.1.7 version of this repository.
**can you please let me know, is there any solution silently acquire new access token without Sign-out the application.**

Below is the response i will get after 1 hour of background or killing the app and open
Request failed with status: 401.
I/flutter ( 9289): {
I/flutter ( 9289): "error": {
I/flutter ( 9289): "code": "InvalidAuthenticationToken",
I/flutter ( 9289): "message": "Access token has expired.",

After oauth.logout() it will work. But every time it will ask to enter user name and password to authenticate, after token expiry every 60 minutes.

I pushed one commit in to the below branch, you can pull that branch give your microsoft credentials, it will fetch response for the first time and after 60 minutes it will give access token expiry error.

https://github.com/Earlybyte/aad_oauth/compare/master...yugandh:Test-Microsoft-Graph-API

One more question after every 60 minutes i am getting same access token, instead of new access token.

**Expected:**
If we already logged in to the app using microsoft azure  email and password, we need to get a new updated access token and it will not give 401 error.

**Test Code:**
Step 1: copy this code in to main.dart file where we authenticate and call  authenticateMyProfile() method to see response in your debug console after 60 minutes.
// Microsoft Graph API call to fetch user profile
Future<void> authenticateMyProfile() async {
  try {
    await oauth.login();
    String accessToken = await oauth.getAccessToken();
    print(accessToken);
    var response = await http.get(https://graph.microsoft.com/v1.0/me, headers: {“Authorization”: “Bearer ” + accessToken});
    if(response.statusCode == 200) {
          print(response.body);

    } else {
      print('$responseStatus ${response.statusCode}.');
    }
  } catch (e) {
    print(e.toString());
  }
}

**Comment by yugandh** [comment]
please read below link.

https://stackoverflow.com/questions/33016400/azure-aad-token-expire-issue-with-web-app

Actual:
In current library we are not updating newly generated access token and always getting old access token after every 60 minutes.

Expected:
New access token should update in model after every 60 minutes

**Comment by alann-maulana** [comment]
By accessing [AadOauth#getAccessToken()](https://github.com/Earlybyte/aad_oauth/blob/master/lib/aad_oauth.dart#L44) will directly request a new token when there is a `refreshToken`. Check this method [AadOauth#_performAuthorization()](https://github.com/Earlybyte/aad_oauth/blob/master/lib/aad_oauth.dart#L62-L81). I'm using this library too, but I got no single problem by using it.

**Comment by behlsoft** [comment]
this feature is not working, AadOauth.tokenIsValid gives false so I call AadOauth,getAccessToken it still gives the old Token which is expired.

`if(!await oauth.tokenIsValid()){
      accessToken =await oauth.getAccessToken();
    }`

**Comment by behlsoft** [comment]
> By accessing [AadOauth#getAccessToken()](https://github.com/Earlybyte/aad_oauth/blob/master/lib/aad_oauth.dart#L44) will directly request a new token when there is a `refreshToken`. Check this method [AadOauth#_performAuthorization()](https://github.com/Earlybyte/aad_oauth/blob/master/lib/aad_oauth.dart#L62-L81). I'm using this library too, but I got no single problem by using it.

any success?

**Comment by alann-maulana** [comment]
@behlsoft can you give me a sample code using dartpad or gist or invite me to your repo, I'll take a look for it. Just now, I'm forking this repo (again), entering my AD credentials at example code and running it well for both Android Emulator and iOS Simulator.

**Comment by behlsoft** [comment]
@alann-maulana it is running well but after 60 min (token expire). I need to login again as it shows token is expired. I am using
`dependencies:
  aad_oauth: "^0.1.7"`

` Config config;
  setUpLogin(){
    
      config = Config(
          "f610c0b7-bd24-4b39-810b-3dc280afb590",
          "035ee15e-e5a9-43a7-83b4-21984566727e",
//          "https://graph.microsoft.com/user.read",
          "api://035ee15e-e5a9-43a7-83b4-21984566727e/Mobile",
          "msauth://anint.who.who_sea/ga0RGNYHvNM5d0SLGQfpQWAPGJ8%3D");
    
    final AadOAuth oauth = new AadOAuth(config);
getDetails(oauth);
}`

`Future getDetails(AadOAuth oauth) async{
    await oauth.login();
    String accessToken = await oauth.getAccessToken();
    print(accessToken.length);
 
   print(await oauth.tokenIsValid());

    if(!await oauth.tokenIsValid()){
      await oauth.login();
      accessToken =await oauth.getAccessToken(); //it again gave me old token
    }
    getDataFromGraphApi(accessToken);
  }`

**Comment by behlsoft** [comment]
> @behlsoft can you give me a sample code using dartpad or gist or invite me to your repo, I'll take a look for it. Just now, I'm forking this repo (again), entering my AD credentials at example code and running it well for both Android Emulator and iOS Simulator.

any update?

**Comment by behlsoft** [comment]
> @alann-maulana it is running well but after 60 min (token expire). I need to login again as it shows token is expired. I am using
> `dependencies: aad_oauth: "^0.1.7"`
> 
> `Config config;`
> `setUpLogin(){`
> `config = Config(`
> `"f61xxxb7-xxx4-xxx1-810b-xxxxxxafv590",`
> `"03xxx15e-xxx9-43xx-03xx-2xxxxx66147e",`
> `"api://xx5exxxx-xxa9-x3xx-xxxx-xxxxxxx/Mobile",`
> `"msauth://xxx.x.x.x/gl0RGxxHvxxxx0SLGQfpQxxxxL8%0D");`
> `final AadOAuth oauth = new AadOAuth(config);`
> `getDetails(oauth);`
> `}`
> 
> `Future getDetails(AadOAuth oauth) async{`
> `await oauth.login();`
> `String accessToken = await oauth.getAccessToken();`
> `print(await oauth.tokenIsValid());`
> `if(!await oauth.tokenIsValid()){`
> `await oauth.login();`
> `accessToken =await oauth.getAccessToken(); //it again gave me old token`
> `}`
> `getDataFromGraphApi(accessToken);`
> `}`

this is my code

**Comment by behlsoft** [comment]
> @behlsoft can you give me a sample code using dartpad or gist or invite me to your repo, I'll take a look for it. Just now, I'm forking this repo (again), entering my AD credentials at example code and running it well for both Android Emulator and iOS Simulator.

waiting for your reply!

**Comment by alann-maulana** [comment]
@behlsoft I think I have found your problem. After deploying our app for a month, we got report error about expired token. And you know what? The refresh token is expired too, a nightmare.

I do fork this repo, and do a lot of update because of this problem. You can check my commits [on Feb 24, 2020](https://github.com/alann-maulana/aad_oauth/commits/master)

**Comment by vladaman** [comment]
on iOS 13.3 using https://github.com/alann-maulana/aad_oauth.git I am requested to login every time I open the app (fresh open or after reboot). This issue is not on Android with the fix.
