### ISSUE TITLE
flutter : A problem occurred configuring project ':flutter_secure_storage'

### ISSUE THREAD

**Issue by tazik561** [Earlybyte/aad_oauth#140]
I am trying to use `aad_oauth: ^0.3.0` on my flutter application . This library seems to need `flutter_secure_storage-4.2` . Now when I want to run my application I got this error:

    A problem occurred configuring project ':flutter_secure_storage'.
    > Could not resolve all artifacts for configuration ':flutter_secure_storage:classpath'.
       > Could not find gradle-3.3.1.jar (com.android.tools.build:gradle:3.3.1).
         Searched in the following locations:
             https://dl.google.com/dl/android/maven2/com/android/tools/build/gradle/3.3.1/gradle-3.3.1.jar
       > Could not find builder-3.3.1.jar (com.android.tools.build:builder:3.3.1).
         Searched in the following locations:
             https://dl.google.com/dl/android/maven2/com/android/tools/build/builder/3.3.1/builder-3.3.1.jar
       > Could not find crash-26.3.1.jar (com.android.tools.analytics-library:crash:26.3.1).
         Searched in the following locations:
             https://dl.google.com/dl/android/maven2/com/android/tools/analytics-library/crash/26.3.1/crash-26.3.1.jar
       > Could not find bundletool-0.6.0.jar (com.android.tools.build:bundletool:0.6.0).
         Searched in the following locations:
             https://dl.google.com/dl/android/maven2/com/android/tools/build/bundletool/0.6.0/bundletool-0.6.0.jar
       > Could not find protos-26.3.1.jar (com.android.tools.analytics-library:protos:26.3.1).
         Searched in the following locations:
             https://dl.google.com/dl/android/maven2/com/android/tools/analytics-library/protos/26.3.1/protos-26.3.1.jar
       > Could not find apkzlib-3.3.1.jar (com.android.tools.build:apkzlib:3.3.1).
         Searched in the following locations:
             https://dl.google.com/dl/android/maven2/com/android/tools/build/apkzlib/3.3.1/apkzlib-3.3.1.jar
       > Could not find apksig-3.3.1.jar (com.android.tools.build:apksig:3.3.1).
         Searched in the following locations:
             https://dl.google.com/dl/android/maven2/com/android/tools/build/apksig/3.3.1/apksig-3.3.1.jar
       > Could not find annotations-26.3.1.jar (com.android.tools:annotations:26.3.1).
         Searched in the following locations:
             https://dl.google.com/dl/android/maven2/com/android/tools/annotations/26.3.1/annotations-26.3.1.jar
       > Could not find databinding-common-3.3.1.jar (androidx.databinding:databinding-common:3.3.1).
         Searched in the following locations:
             https://dl.google.com/dl/android/maven2/androidx/databinding/databinding-common/3.3.1/databinding-common-3.3.1.jar
       > Could not find baseLibrary-3.3.1.jar (com.android.databinding:baseLibrary:3.3.1).
         Searched in the following locations:
             https://dl.google.com/dl/android/maven2/com/android/databinding/baseLibrary/3.3.1/baseLibrary-3.3.1.jar
       > Could not find aapt2-proto-0.3.1.jar (com.android.tools.build:aapt2-proto:0.3.1).
         Searched in the following locations:
             https://dl.google.com/dl/android/maven2/com/android/tools/build/aapt2-proto/0.3.1/aapt2-proto-0.3.1.jar
    
    Possible solution:
     - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html

This is my gradle :

    def localProperties = new Properties()
    def localPropertiesFile = rootProject.file('local.properties')
    if (localPropertiesFile.exists()) {
        localPropertiesFile.withReader('UTF-8') { reader ->
            localProperties.load(reader)
        }
    }
    
    def flutterRoot = localProperties.getProperty('flutter.sdk')
    if (flutterRoot == null) {
        throw new GradleException("Flutter SDK not found. Define location with flutter.sdk in the local.properties file.")
    }
    
    def flutterVersionCode = localProperties.getProperty('flutter.versionCode')
    if (flutterVersionCode == null) {
        flutterVersionCode = '1'
    }
    
    def flutterVersionName = localProperties.getProperty('flutter.versionName')
    if (flutterVersionName == null) {
        flutterVersionName = '1.0'
    }
    
    apply plugin: 'com.android.application'
    apply plugin: 'kotlin-android'
    apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"
    
    android {
        compileSdkVersion 30
    
        sourceSets {
            main.java.srcDirs += 'src/main/kotlin'
        }
    
        defaultConfig {
            // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
            applicationId "com.example.app"
            minSdkVersion 18
            targetSdkVersion 30
            versionCode flutterVersionCode.toInteger()
            versionName flutterVersionName
        }
    
        buildTypes {
            release {
                // TODO: Add your own signing config for the release build.
                // Signing with the debug keys for now, so `flutter run --release` works.
                signingConfig signingConfigs.debug
            }
        }
    }
    
    flutter {
        source '../..'
    }
    
    dependencies {
        implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    }

This is doctor output:

    Doctor summary (to see all details, run flutter doctor -v):
    [✓] Flutter (Channel stable, 2.8.1, on Debian GNU/Linux 10 (buster) 4.19.0-18-amd64, locale en_US.UTF-8)
    [✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    [✓] Chrome - develop for the web
    [✓] Android Studio (version 2020.3)
    [✓] Android Studio
    [✓] VS Code (version 1.63.2)
    [✓] Connected device (2 available)

This is my environment:

    environment:
      sdk: ">=2.15.0 <3.0.0"
    
    dependencies:
      aad_oauth: ^0.3.0
      cupertino_icons: ^1.0.2
      dio: ^4.0.4

**Comment by vietmy1711** [comment]
Hi, I clone the project and did changed the `flutter_secure_storage` to `5.0.2`, you can add it to your project with this:

`  aad_oauth:
      git:
        url: https://github.com/vietmy1711/aad_oauth
`
