### ISSUE TITLE
Invalid Signature When Using Oauth ID Token to verify with Azure-AD-Verify-Token Library

### ISSUE THREAD

**Issue by voyager163** [Earlybyte/aad_oauth#143]
I am facing issue in verifying my oauth ID token. I have proven that the API side is correct by using postmaster to extract the id token of a email.

When i use the id token obtain from the aad_oauth, i am facing a error "JWTVerification:: Error JsonWebTokenError: invalid signature". Based on the a closed ticket, the person say about a missing dot but i have no idea how he has managed to resolved it.

However, if i use the postmaster obtained JWT token, it will show that it is a verified token and have a verified signature.

**Comment by ricardonolan** [comment]
We're having the same issue:
"code":"InvalidAuthenticationToken","message":"CompactToken parsing failed with error code: 80049217"

**Comment by voyager163** [comment]
I tried the old libraries but still no use. I did a work around. I call firebase Azure AD login and pull the token from cloud storage for the API to authenticate

**Comment by med1990** [comment]
hello @voyager163 did you find away to handle the issue?
