### ISSUE TITLE
Can i add multiple scopes at one time login.

### ISSUE THREAD

**Issue by yugandh** [Earlybyte/aad_oauth#15]
Currently we are adding single scope, Is it possible to add multiple scopes at one time access.
  
static final Config config = new Config(tenantId, applicationId, "https://graph.microsoft.com/user.read", redirectUrl);

In above code we are passing only one scope user.read, and if i want to pass another scope File.read  in same login call then we need to pass as array of strings.
currently this framework is will take only one string.

In below link which is iOS native support microsoft sdk for azure authentication Graph API, they are passing multiple scopes as an array of Strings. (search for string scopes in below reference link)
https://docs.microsoft.com/en-us/azure/active-directory/develop/quickstart-v2-ios

**Comment by yugandh** [comment]
please read below link.

https://stackoverflow.com/questions/33016400/azure-aad-token-expire-issue-with-web-app

Actual:
In current library we are not updating newly generated access token and always getting old access token after every 60 minutes.

Expected:
New access token should update in model after every 60 minutes.

**Comment by alann-maulana** [comment]
@yugandh you need to use config like this below to user multiple scope at login :
```dart
final aad.Config _config = aad.Config(
  "AZURE_TENNANT_ID",
  "CLIENT_ID",
  "openid profile offline_access User.Read Calendars.Read Calendars.Read.Shared Calendars.ReadWrite Calendars.ReadWrite.Shared Mail.Send",
  "REDIRECT_URI",
);
final AadOAuth oauth = new AadOAuth(_config);
```
> split a different scope with whitespace
