### ISSUE TITLE
Problem with B2C usage

### ISSUE THREAD

**Issue by angelocacaceMSC** [Earlybyte/aad_oauth#161]
I am trying to integrate my Flutter app with azure identity. In particular we are trying to use B2C, but without obtaining particular results.

When I click the "Login" button, the page remains blank and the following message appears in the debug console:

![MicrosoftTeams-image (11)](https://user-images.githubusercontent.com/110967010/183840547-75009069-49b0-455e-9f1a-b28c96e8b396.png)

I also show you the configuration parameters used:
![183840847-6b3b666f-0ae5-4c65-b62a-d8126626e091](https://user-images.githubusercontent.com/7951747/183847704-07261e10-788b-41e2-be3e-6f7566ff4d3c.png)

We can't understand if it's a configuration parameter problem, or a library problem.
We look forward to your support.

Good day and good job.

EDIT: Removed your clientSecret

**Comment by josemiguelvarela** [comment]
Hi,

Sorry for the late reply. I'm not sure if the 'tenant' is right, try with 'cetrulogam' instead of 'cetrulogam.onmicrosoft.com'. This is the only difference I see with our working example.
