### ISSUE TITLE
Please make a working example (native & web) based on Microsoft Azure

### ISSUE THREAD

**Issue by RoarGronmo** [Earlybyte/aad_oauth#167]
When fighting with this issue (https://github.com/Earlybyte/aad_oauth/issues/166) I see some lack of information and preferably a best-practice step-by-step working example to get both native (android, ios, ) and web to work seamlessly.

If you could provide that at earlybyte, I think far more users will be confident with your approach to accessing Microsoft Azure resources.

Please ?

**Comment by josemiguelvarela** [comment]
Thank you for your feedback. We'll try to improve the documentation for the web version.
