### ISSUE TITLE
Always retrieve:  The request body must contain the following parameter: 'client_assertion' or 'client_secret'.

### ISSUE THREAD

**Issue by CristianTurcios** [Earlybyte/aad_oauth#17]
Hello, I was creating an integration with this widget

When I putting my tenant and client id and try to log in via o365 I always receive this error:

> Error during token request: invalid_client: AADSTS7000218: The request body must contain the following parameter: 'client_assertion' or 'client_secret'.

I was configured my app in azure in this way

[Scopes](https://storage.googleapis.com/portal-assets-prod/Captura111.PNG)

and when I build the Config constructor look like this:

`final Config config = new Config(
      "YOUR TENANT ID",
      "YOUR CLIENT ID",
      "openid profile offline_access",
      "https://login.live.com/oauth20_desktop.srf"
    );`

and my app look like this:

[App](https://storage.googleapis.com/portal-assets-prod/2019-05-31_1614.png)

Someone can help me and tell me what's wrong in my app in azure or if is an issue with the widget #

**Comment by yugandh** [comment]
@CristianTurcios 

I think there might be an issue in azure portal settings of redirect URI and openid profile offline_access.

  static final Config config = new Config("YOUR_TENANT_ID", "YOUR CLIENT ID", "openid profile offline_access", "redirect uri",);


openid profile offline_access = "https://graph.microsoft.com/user.read"


redirectUri = "msal00dgfsdgfdsgsdfgfdsgfdsgdfsgfdsg://auth" (to find this in your azure portal click on your app in azure portal and click on authentication, you will see redirect URL's page )

Find below text 
If you are using the Microsoft Authentication Library (MSAL) or the Active Directory Authentication Library (ADAL) to build applications for desktop or mobile devices, you may select from the suggested Redirect URIs below or enter a custom redirect URI above. For more information, refer to the library documentation.

I assume there will be three checkmark options and select first option and save, that will be your redirect URI and copy that and paste in your app.

Reference:
https://docs.microsoft.com/en-us/azure/active-directory/develop/quickstart-register-app

**Comment by CristianTurcios** [comment]
Hello @yugandh 

Thanks for your quickly answer

I am so confused about the "openid profile offline_access", so sorry about my stupids questions

[this is my actual config](https://storage.googleapis.com/portal-assets-prod/2019-05-31_1653.png) (I will generate new tenan and client id in the future, for that I show this here)

my configurations are right o I need put other values there?

Also I found the redirectUri that you mentioned in my azure portal and I replaced that: [here](https://storage.googleapis.com/portal-assets-prod/2019-05-31_1653_001.png)

And finally I saw an option of Certificates and secrets so I generated a new client secret [here](https://storage.googleapis.com/portal-assets-prod/2019-05-31_1653_002.png)

But the app continue show me the same error: 

> Error during token request: invalid_client: AADSTS7000218: The request body must contain the following parameter: 'client_assertion' or 'client_secret'.

Sorry if my questions are very basic or I could not understand any idea of your first comment

**Comment by yugandh** [comment]
reference for "openid profile offline_access" which means scopes of the graph API.
For example if you just want to read the basic profile information you can add "openid profile offline_access" = "https://https://graph.microsoft.com/user.read"

or add "https://graph.microsoft.com/Files.Read.All"  for one drive files access from graph api.

Read below reference to understand the scopes of microsoft graph api.
Reference:
https://docs.microsoft.com/en-us/graph/permissions-reference

https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-permissions-and-consent


using graph api you can get json response of your data and can show in your app:
Reference: 
https://github.com/Earlybyte/aad_oauth/compare/master...yugandh:Test-Microsoft-Graph-API

![Screen Shot 2019-05-31 at 4 13 56 PM](https://user-images.githubusercontent.com/14207417/58739463-22f53c00-83bf-11e9-8a75-9fea3592c39f.png)



Regarding certificates and client secrets you can ignore, not needed for now.
client secret is useful in firebase microsoft outlook authentication setUP. currently for flutter outlook auth is not yet added. for native ios and android outlook authentication is there and working fine.

reference:
https://firebase.google.com/docs/auth/ios/microsoft-oauth

**Comment by CristianTurcios** [comment]
Awesome explication, I understood now

thanks a lot for your time and for your explication!

I will close the issue now
