### ISSUE TITLE
Not working on iOS

### ISSUE THREAD

**Issue by royalGriffin22** [Earlybyte/aad_oauth#2]
Same code is working fine on Android devices, and the Azure portal opens, but on iOS nothing happens, with no error.
Code:
```final AadOAuth oauth = new AadOAuth(config);
      await oauth.login();
      String accessToken = await oauth.getAccessToken();
      print("After login. Token : " + accessToken);

**Comment by tobiasmeier78** [comment]
Hi,

thank you for submitting a bug. Currently we are working on another project and unfortunately we don't have the time it usually takes to maintain such a library.

If you want to participate on the code we are open to discuss about it.

best regards

**Comment by vitorbg2** [comment]
this is a webview issue on IOS, you need to set the webview screen size to  screen's 95%, like that:
```
Size size = MediaQuery.of(_scaffoldKey.currentContext).size;
oauth.setWebViewScreenSize(new Size(size.width, size.height * 0.95));
//and then..
await oauth.login();
String accessToken = await oauth.getAccessToken();
print("After login. Token : " + accessToken);
```
