### ISSUE TITLE
Custom parameters to support dynamic UI customization for B2C custom policies

### ISSUE THREAD

**Issue by justoke** [Earlybyte/aad_oauth#203]
**Preface**
I'd like to propose an enhancement to enable support for dynamic UI customization. This is useful where you may want to provide custom UI to users in a white label mobile app using the Azure B2C custom policies. The idea is that based on a location you might provide a customized UI to the users. This is possible using custom policies under the Identity Experience Framework on Azure B2C and is facilitated by passing custom query string parameters as part of your authorization url. 

The Azure B2C documentation describes this use case
[Dynamic UI customization](https://learn.microsoft.com/en-us/azure/active-directory-b2c/claim-resolver-overview#dynamic-ui-customization)

**Custom UI templates**
UI web templates which include html, CSS, images and java script resources are stored under named folders on web server or Azure blob storage container. Multiple parameters can be passed and mapped to claims within the B2C framework. The display custom UI elements relies on using the parameter to map to a server path a specific folder that contains your UI elements. For example, a sign up and sign in form would be location under a folder per support custom UI:
Claim defined in custom policy and substituted at run time by the B2C policy framework.
root\{OAUTH-KV:locationId}\template
Web server UI components organised by location
root\location1\template\signupin.html
root\location2\template\signupin.html

**What is needed in aad_oath?**
Current implementation is not possible as there is no way to attach the custom query parameters to the authorizationUrl, due to lack of public accessors to the parameters collection. I tried appending a query parameter to the authScope parameter but although this works it breaks the retrieval of the authentication code.

**Mobile app code**
Create a map of key values that will be appended to the url as query string parameters
`_customParameters.addAll({'locationId': 'default'});`

**aad_oath Config**
The Config model would need a string or map of parameters, which are key value pairs that will be appended to the authorizationurl
 in the RequestCode class. 
Add a map for the key value pairs
final Map<String, String> customParameters;

The map can then be converted to an additional set of query string parameters appended to the request url:
'${_authorizationRequest.url}?$urlParams&$urlCustomParams'

![image](https://user-images.githubusercontent.com/26506785/213778285-cdd9624c-3d79-43c3-89eb-fb8e2380683f.png)

I have tested this implementation in a mobile app using latest Flutter SDK 3.3.10 using custom location templates to achieve a branded user experience based on a location identifier.

I'd be happy to provide a pull request for this enhancement.

**Comment by stevenebutler** [comment]
Please submit the PR.

**Comment by Painwraith** [comment]
Thank you for doing this, was just looking for this.

**Comment by justoke** [comment]
@stevenebutler  I've got the code ready, but I can't publish my branch to the repo. How would you like me to do this?

**Comment by stevenebutler** [comment]
Hi @justoke. The normal way to do this on github is to fork the repository into your own copy then make the change on a branch there. Once you have pushed to your own github repository the github UI provides a way to submit that as a PR back to the original repository.
