### ISSUE TITLE
Exception on revoked token not caught

### ISSUE THREAD

**Issue by einatguri** [Earlybyte/aad_oauth#208]
In this function -  when password changes, the token is revoked and then it throws the exception here inside the `map['error'] != null` block. 
But this exception is not caught by anything. 
The UI changes the correct screen, but since the exception is not caught, i have no way of knowing this happened so i have a loader. 

when calling:
```
try {
 await _aadAuth.login(refreshIfAvailable: true);
} catch (error){  
//NOT GETTING HERE
}
```

in `lib/model/token.dart` 

```
static Token fromMap(Map<String, dynamic>? map) {
    if (map == null) throw Exception('No token from received');
    //error handling as described in https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-auth-code-flow#error-response-1
    if (map['error'] != null) {
//THIS IS NOT CAUGHT BY ANYTHING
      throw Exception('Error during token request: ' +
          map['error'] +
          ': ' +
          map['error_description']);
    } else {
      var model = Token();
      model.accessToken = map['access_token'];
      model.tokenType = map['token_type'];
      model.expiresIn = map['expires_in'] is int
          ? map['expires_in']
          : int.tryParse(map['expires_in'].toString()) ?? 60;
      model.refreshToken = map['refresh_token'];
      model.idToken = map.containsKey('id_token') ? map['id_token'] : '';
      model.issueTimeStamp = DateTime.now().toUtc();
      model.expireTimeStamp = map.containsKey('expire_timestamp')
          ? DateTime.fromMillisecondsSinceEpoch(map['expire_timestamp'])
          : model.issueTimeStamp
              .add(Duration(seconds: model.expiresIn! - model.expireOffSet));

      return model;
    }
  }
```

**Comment by josemiguelvarela** [comment]
Hi @einatguri ,

Check latest example.

```
final result = await oauth.login();
result.fold(
  (failure) => showError(failure.toString()),
  (token) => showMessage('Logged in successfully, your access token: $token'),
);
String accessToken = await oauth.getAccessToken();
```

failure contains a field named errorType.
```
enum ErrorType {
  AccessDeniedOrAuthenticationCanceled,
  InvalidJson,
  Unsupported,
  UnexpectedError,
}
```

**Comment by einatguri** [comment]
@josemiguelvarela i tried this. 
It doesn't return a result, an error is thrown but not caught, so it's just stuck there. The result is neither a failure or a token, there just isn't one

**Comment by josemiguelvarela** [comment]
Ok, I understand what you mean. When the refreshToken fetch fails, the plugin initiates a full authentication flow without launching any exception.
```
if (token.hasRefreshToken()) {
      final result =
          await _requestToken.requestRefreshToken(token.refreshToken!);
      //If refresh token request throws an exception, we have to do
      //a fullAuthFlow.
      result.fold(
        (l) => token.accessToken = null,
        (r) => token = r,
      );
    }

    if (!token.hasValidAccessToken()) {
      final result = await _performFullAuthFlow();
```

Do you need a different behavior? When the full authentication flow is finished it should return the new token.

**Comment by einatguri** [comment]
@josemiguelvarela I need this exception to be thrown in order to dismiss the loader. 
I have a loader overlay while the system tries to log in, when a result is returned I dismiss the loader. What happens now, is the flow is initiated but since no exception is thrown there is nothing to dismiss the loader overlay so the user is stuck. However, if i don't add the loader there is no indication to the user that something is happening during the login and it feels like the app is frozen. 
Does that make sense ?

**Comment by einatguri** [comment]
@josemiguelvarela mobile

**Comment by einatguri** [comment]
@josemiguelvarela looking forward to hearing from you, thank you for the fast response and great package!

**Comment by josemiguelvarela** [comment]
Hi @einatguri ,

I have been testing this problem and if I force the exception to be thrown in `map['error'] != null` it is correctly returning the error through the failure. The error I get is:
`RequestFailure(ErrorType.InvalidJson, Token json is invalid: type 'Null' is not a subtype of type 'String')`

This is returned through  ` (failure) => showError(failure.toString()),`
```
final result = await oauth.login();
result.fold(
  (failure) => showError(failure.toString()),
  (token) => showMessage('Login successful, your access token: $token'),
);
```

Could you post your code? 
```
try {
 await _aadAuth.login(refreshIfAvailable: true);
} catch (error){  
//NOT GETTING HERE
}
```
This code will not work because the exception has already been caught by the plugin and is dealt with by returning a `Failure` object to the user.

**Comment by einatguri** [comment]
@josemiguelvarela Thanks for the response. 
I tried this but there is no failure nor success.. the result just simply doesn't return anything. 
This is the code: 




     ```
try {
      _aadAuth = AadOAuth(aadConfig);
      final result = await _aadAuth.login(refreshIfAvailable: true);
 result.fold((failure) {
//THIS BLOCK IS NEVER REACHED
      _navigationService.showFullScreenLoader();
        FLog.error(
            text: 'aad login failed: ${failure.message}',
            className: 'auth manager',
            methodName: 'aadLogin');
        if (failure.errorType ==
            ErrorType.AccessDeniedOrAuthenticationCanceled) {
             print('user cancelled');

        }
      }, (token) {
//THIS BLOCK IS NEVER REACHED
          print('token received');
});
      _navigationService.showFullScreenLoader();
      final userMenu = await _completeAadLogin(aadAuth: _aadAuth, role: role);
      return userMenu;
    } catch (e) {
//THIS BLOCK IS ALSO NEVER REACHED

      _navigationService.removeFullScreenLoader();
      FLog.error(
          text: 'aad login error  $e',
          className: 'auth manager',
          methodName: 'aadLogin');
      throw MobittiException('$e');
    }
```

**Comment by josemiguelvarela** [comment]
Hi @einatguri ,

I've tried your code and I can't reproduce the issue (with FLog, _navigationService and userMenu lines commented).

Sorry for not being more helpful. You can upload to Github a sample app that reproduces the problem so I can take a look at this issue.

Also, try to copy the example code without the loader and add your changes gradually, or test your changes in the example app.
