### ISSUE TITLE
Auto popping after AAD login on Flutter IOS 16

### ISSUE THREAD

**Issue by razaen801** [Earlybyte/aad_oauth#211]
I have integrated aad login on my flutter app. The login flow works normally in each android platform whereas in IOS platform (tried on iphone 14 pro- ios 16) after successful login the wizard generates a pop which results in black screen. I have individually breakpointed every step but it seems that the wizard is resulting this pop. 

Can anyone help me on this ?

**Comment by razaen801** [comment]
Also there is no any error/message on console.

**Comment by josemiguelvarela** [comment]
Hi @razaen801 ,

Could you paste the minimum code needed to reproduce this issue?

**Comment by razaen801** [comment]
`/// AAD Login starts
        /// throws exception if login fails
        final tokenData = await AADAuthenticationHelper().startLogin(); // Singleton class that has all the credentials and login
        await tokenData.fold((failure) {
          emit(
            state.copyWith(
                loginStatus: =LoginStatus.error,
                errorData: ErrorData(title: "Sorry", message: "Authentication failed")),
          );
        }, (token) async {
// navigate to the dashboard after some api calls
});`

Hi @josemiguelvarela Looks something like this. Also if i dont do anything after token success it automatically pops here

**Comment by josemiguelvarela** [comment]
Is this line right?
`loginStatus: =LoginStatus.error,`

Other than that, your code looks good. I tested the code on an iPhone 14 Pro Max, but I can't reproduce the issue. Have you tried running the sample app? Does it work correctly or does it reproduce the same issue?

**Comment by razaen801** [comment]
No that is something that came up while pasting here. Is there any new credentials that are added in config? I dont know why I am getting this issue.

**Comment by razaen801** [comment]
@josemiguelvarela i found the issue here. It was because of the redirect url which was pointed to our backend server. It is resolved when pointed to the azure live 'https://login.live.com/oauth20_desktop.srf' and added to server as well. Thank u jmv :D

**Comment by razaen801** [comment]
Happy coding.
