### ISSUE TITLE
Token is not valid (JWT)

### ISSUE THREAD

**Issue by med1990** [Earlybyte/aad_oauth#212]
Hello guys, 

I had the famous problem: The token is not valid (JWT), I think it's because of the signature. 
Has anyone had the same problem and found a solution?

**Comment by RoarGronmo** [comment]
Have seen similar in web, normally if the token has timed out, but when refreshing it this way:
```
if((accessToken==null)||(Jwt.isExpired(accessToken))){
      if(silent == false) Message.warning("Access token expired or not valid, attempting to refresh access token...", durationSeconds: 2);
      var result = await aadOAuth.login(refreshIfAvailable: true);
      result.fold(
              (left){
                Message.error("${left.message}\nYou may need to restart to login successfully");
                return null;
              },
              (right){
                if(silent == false) Message.info("Access token just refreshed successfully...");
                accessToken = right.accessToken;
                print("new accessToken = $accessToken");
              }
      );
    }

```
... it seems to return the same accessToken, even if it is expired, they may deem it valid even if it isn't so..?

`refreshIfAvailable` is set to `true`, AFAIK this should also force a refresh if it is expired, and even bring up the login if the refreshToken is expired. At least it says so...

![image](https://user-images.githubusercontent.com/11217296/229709426-2c23c8e3-2323-4cc9-b381-913dc1f77985.png)
