### ISSUE TITLE
How to disable back button on ANDROID while user is not completely logged in ??

### ISSUE THREAD

**Issue by DanishKhalique** [Earlybyte/aad_oauth#213]
I need to stop the user from pressing the back button until the user is completely logged in.

My App gets stuck at the Splash screen if the user presses the back button during the login screen!!

or Is there any workaround to avoid this ?

https://user-images.githubusercontent.com/61799810/218432975-fd3fdda5-6d63-437d-bda8-a4f1e876a68f.mov

**Comment by josemiguelvarela** [comment]
Hi @DanishKhalique,

What we do is to relaunch the login or display a required login message.
When the user clicks back, you will receive an `ErrorType.AccessDeniedOrAuthenticationCanceled` in the failure.
