### ISSUE TITLE
How to  fetch profile ?

### ISSUE THREAD

**Issue by jay-web** [Earlybyte/aad_oauth#22]
In my project, I am able to receive token using oauth.getAccessToken() function. But don't get any option to fetch profile after login. Please suggest.
final Config config = new Config(
        _tenantName,
        _appId,
        "openid profile offline_access",
       _redirectUrl,
     
    );

    final AadOAuth oauth = new AadOAuth(config);
    await oauth.login();
    String accessToken = await oauth.getAccessToken();

**Comment by yugandh** [comment]
you need to use microsoft graph api and pass the access token.

example:
  static const userProfileBaseUrl = 'https://graph.microsoft.com/v1.0/me';
  static const authorization = 'Authorization';
  static const bearer = 'Bearer ';

  // Microsoft Graph API call to fetch user profile
  Future<UserProfile> authenticateMyProfile() async {
    try {
      await oauth.login();
      String accessToken = await oauth.getAccessToken();
      print(accessToken);
      var response = await http.get(userProfileBaseUrl,
          headers: {authorization: bearer + accessToken});
      print(response.body);
    } catch (e) {
      print(e.toString());
    }
    return null;
  }

**Comment by jay-web** [comment]
Hi, thank you for your response. I implemented your suggested code and now getting this error :
profile is {
 "error": {
  "code": "InvalidAuthenticationToken",
  "message": "Access token validation failure. Invalid audience.",
  "innerError": {
  "request-id": "d17ad358-5617-4183-97da-12037cbf754b",
  "date": "2019-06-24T11:31:38"
    }
   }
}

Even when i change the request url to https://graph.windows.net, so getting error 
{"odata.error":{"code":"Authentication_MissingOrMalformed","message":{"lang":"en","value":"Access Token missing or malformed."}}}

**Comment by yugandh** [comment]
Hi,

follow below link for how to set up and get details from azure account.
https://github.com/Earlybyte/aad_oauth/issues/17

**Comment by jay-web** [comment]
Hi, I checked the reference link which you mentioned above comment and it helped me to fetch profile. But when I check the access token, it is without payload. So it becomes an invalid token for further process.

**Comment by yugandh** [comment]
Hi,
i think you are facing below issue. currently i am storing user profile in shared preferences when i first time login in to the app and using those. Accesstoken is expiring after 60 minutes and not getting new token.

https://github.com/Earlybyte/aad_oauth/issues/14

**Comment by jay-web** [comment]
Hi
I checked the token at the same time not (after 60 min) on jwt.io site.
Result is invalid and no payload.

**Comment by yugandh** [comment]
According to your error logs, this issue is with your redirect url.

can you post your redirect url, what you are using . do not post entire redirect url for security reason. just send me half of the url what are using.

redirectUri = "msal00dgfsdgfdsgsdfgfdsgfdsgdfsgfdsg://auth" (to find this in your azure portal click on your app in azure portal and click on authentication, you will see redirect URL's page )

**Comment by jay-web** [comment]
Redirecturl- https://login.windows.net/common.onmicrosoft.com
I changed later words, due to security reasons.

**Comment by yugandh** [comment]
you need to use redirect url like below. click on checkmark similar to below msal://dggdd//auth

<img width="1332" alt="Screen Shot 2019-06-28 at 1 21 59 PM" src="https://user-images.githubusercontent.com/14207417/60369250-d98d1200-99a7-11e9-8f93-e85e4f4a0e3f.png">

**Comment by jay-web** [comment]
I got this redirect url from my client. They already running cordova based
mobile app, using same url which I sent you and which is working very fine
from last one year with ADAL auth. Now I am creating that same mobile aap
in flutter, and facing this issue.

**Comment by yugandh** [comment]
For testing purpose can you please, create your own azure account with hotmail and check, this repo will work.
one more thing is coredova which do you have is using v1 or v2 end point?
Below is the ios native framework, you can use for testing.
https://github.com/Azure-Samples/active-directory-ios-swift-native-v2

**Comment by vladaman** [comment]
Hi, I tried the authenticateMyProfile above and I get following result after I get token:

```
I/flutter (12055): {
[        ] I/flutter (12055):   "error": {
[        ] I/flutter (12055):     "code": "Authorization_RequestDenied",
[        ] I/flutter (12055):     "message": "Insufficient privileges to complete the operation.",
[        ] I/flutter (12055):     "innerError": {
[        ] I/flutter (12055):       "request-id": "xxxxxxxx-c1cf-4530-90c5-b26ba98da96b",
[        ] I/flutter (12055):       "date": "2019-09-22T16:00:53"
[        ] I/flutter (12055):     }
[        ] I/flutter (12055):   }
[        ] I/flutter (12055): }
```

**Comment by Sankaranis** [comment]
@yugandh Thanks for the help, below code is working fine me to get the user info

  Client _client = Client();
      final graphResponse = await _client.get(
          'https://graph.microsoft.com/v1.0/me',
          headers: {HttpHeaders.authorizationHeader: "Bearer $accessToken"});
      print(graphResponse.body);

**Comment by Refaydeen** [comment]
Is anyone have a solution for sso ,when a user logging first time I need user email after that when second time user logging in means I need to navigate to dashboard but on that time also I need user email how to do that

**Comment by Test18415** [comment]
> Hi, I tried the authenticateMyProfile above and I get following result after I get token:
> 
> ```
> I/flutter (12055): {
> [        ] I/flutter (12055):   "error": {
> [        ] I/flutter (12055):     "code": "Authorization_RequestDenied",
> [        ] I/flutter (12055):     "message": "Insufficient privileges to complete the operation.",
> [        ] I/flutter (12055):     "innerError": {
> [        ] I/flutter (12055):       "request-id": "xxxxxxxx-c1cf-4530-90c5-b26ba98da96b",
> [        ] I/flutter (12055):       "date": "2019-09-22T16:00:53"
> [        ] I/flutter (12055):     }
> [        ] I/flutter (12055):   }
> [        ] I/flutter (12055): }
> ```

Add User.Read to scope
