### ISSUE TITLE
Add token validation method to the plugin

### ISSUE THREAD

**Issue by Zazo032** [Earlybyte/aad_oauth#223]
Having a helper method like the one defined in https://github.com/Earlybyte/aad_oauth/issues/209#issuecomment-1430345304 might be useful to directly check within the library if the token is still valid.

This will help having a unified way to check if the token that we have received from `getAccessToken()` is still a valid one. If it's expired, `login(refreshIfAvailable: true)` should be called to try to refresh the current token. If that fails, the user is no longer logged in and should re-login again.

**Comment by josemiguelvarela** [comment]
Can anyone create a pull request for this please?
