### ISSUE TITLE
Try to renew session with `refresh_token` before opening web page

### ISSUE THREAD

**Issue by enricobenedos** [Earlybyte/aad_oauth#224]
We are looking for a way to manage the possibility to refresh the login without necessarily start the AAD B2C flow, we want to manage the case in which refresh token is not valid.

At the moment there is the possibility to ask for a login refresh in this way: `oauth.login(refreshIfAvailable: true)`. 
This great feature has some limits because we need to decide if open the web page once we know if refresh token was enough or not. 

**Example:** user has logged in and now can use the app for 60 minutes(access token validity). After  >60 minutes the app need to login a new time to interact with the API, so let's call `oauth.login(refreshIfAvailable: true)`. At this point if refresh token is still valid the login will be performed silently else the web page will appear.

The problem is that we want to manage the case in which also refresh token isn't enough.

**Comment by OssiPesonen** [comment]
> We are looking for a way to manage the possibility to refresh the login without necessarily start the AAD B2C flow, we want to manage the case in which refresh token is not valid.
> 
> At the moment there is the possibility to ask for a login refresh in this way: `oauth.login(refreshIfAvailable: true)`. This great feature has some limits because we need to decide if open the web page once we know if refresh token was enough or not.
> 
> **Example:** user has logged in and now can use the app for 60 minutes(access token validity). After >60 minutes the app need to login a new time to interact with the API, so let's call `oauth.login(refreshIfAvailable: true)`. At this point if refresh token is still valid the login will be performed silently else the web page will appear.
> 
> The problem is that we want to manage the case in which also refresh token isn't enough.

Refresh tokens exist to refresh the access token. If it has expired, a new login is required to get a new one. This can also happen if the refresh token has been invalidated by the authorization server due to malicious use detection. Auth0, for example, does this if two refresh tokens have been issued.
