### ISSUE TITLE
Save last login information

### ISSUE THREAD

**Issue by alon-engineer** [Earlybyte/aad_oauth#228]
How can I configure the login method to redirect to the `login()` page each time it is called and see the last login information without having to re-enter the username and password each time?

**Comment by alon-engineer** [comment]
@josemiguelvarela @erickdaros @sladomic @tigloo @loetsphi @stevenebutler @JenishMS @graknol @yugandh @Zazo032 @lhamycodes @vinothrao @vasbaz @jstepaniakobj @joshryandavis @ashusilswal @bradleybeighton @ruamberg @gitter-badger

**Comment by tigloo** [comment]
If you want to force the login page being shown, you can call logout() before login().

Since authentication is done in a web view, you have no control over user names being pre-filled. This is entirely controlled by the user's own setup.

**Comment by alon-engineer** [comment]
Thank you for your reply. @tigloo 
But for some AD login, it seems to keep my last login information, and your practice will cause me to re-enter my username and password every time I enter the login page. 
Like caching the last login information through a cookie?

**Comment by alon-engineer** [comment]
Is it possible to support jumping to offer to select a saved account the next time I log in after having logged in, like the native iOS app?

@josemiguelvarela @erickdaros @sladomic @tigloo @loetsphi @stevenebutler @JenishMS @graknol @yugandh @Zazo032 @lhamycodes @vinothrao @vasbaz @jstepaniakobj @joshryandavis @ashusilswal @bradleybeighton @ruamberg @gitter-badger

**Comment by tigloo** [comment]
I suggest to familiarize yourself with the Microsoft Authentication Library (https://learn.microsoft.com/en-us/azure/active-directory/develop/msal-overview, https://github.com/AzureAD/microsoft-authentication-library-for-js) as well as Azure AD (referenced from both links) to see the capabilities of Azure AD and which options you need to achieve which behavior.

I can only reiterate that authentication is achieved through a web view and saving accounts in a web view is controlled by the browser showing that web view. What the browser can or can not do is usually controlled by the user or the system. You could try instantiating your own, internally configured browser to achieve what you want but that is most likely beyond the scope of this package.

Note that the issue tracker is not a support forum and repeatedly mentioning all contributors to this package is usually considered rude as you are spamming random people who are not affiliated with the package.

**Comment by alon-engineer** [comment]
Thank you so much for the update and here's a big sorry for the interruption to all the contributors.
I didn't realize it and I'm very sorry for bothering all the contributors.
