### ISSUE TITLE
Not able to login into web

### ISSUE THREAD

**Issue by yudhisthira123** [Earlybyte/aad_oauth#234]
I am trying to integrate in my web app and following all the steps given in documentation. But unfortunately not able to login successfully. Screen shot is attached for information. This issue happens when call login again after redirection. Please help me.

<img width="1136" alt="Screenshot 2023-05-15 at 11 55 25" src="https://github.com/Earlybyte/aad_oauth/assets/19162874/7c494c3e-3940-4767-894a-a6b38f819e1a">

**Comment by josemiguelvarela** [comment]
Hi @yudhisthira123,

Are you using "Mobile and desktop applications" when you add the platform in Azure?
![image](https://github.com/Earlybyte/aad_oauth/assets/65731763/12b2e267-7928-4873-864a-3a46e0989cbb)

**Comment by yudhisthira123** [comment]
Yes, I am using "Mobile and desktop applications".

**Comment by CanadianN1nj4** [comment]
Make sure you have the redirect URL allowed for web. And then also ensure you're launching from the same URL on web. You should be able to do that using --web-port=
