### ISSUE TITLE
White screen on login

### ISSUE THREAD

**Issue by emaborsa** [Earlybyte/aad_oauth#240]
Hi all,

I checked out the repo, run `flutter pub get`, set the props in the `b2c` example:

```
 static final Config configB2Ca = Config(
      tenant: 'myTenant.onmicrosoft.com',
      clientId: 'f8a485e0-e8b8-4d98-b60d-acXXXXXXXXX',
      scope: 'ascope',
      isB2C: true,
      navigatorKey: navigatorKey,
      policy: 'b2c_1a_production_signin',
      loader: SizedBox());
```

The app runs (Android), when I click on `login` a white screen appears and stays there until I click back. 
In the log I find a message (blue):

`E/chromium(24451): [ERROR:ssl_client_socket_impl.cc(992)] handshake failed; returned -1, SSL error code 1, net_error -200`

[√] Flutter (Channel stable, 3.7.8, on Microsoft Windows [Versione 10.0.19044.2846], locale it-IT)
    • Flutter version 3.7.8 on channel stable at C:\Source\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 90c64ed42b (9 weeks ago), 2023-03-21 11:27:08 -0500
    • Engine revision 9aa7816315
    • Dart version 2.19.5
    • DevTools version 2.20.1

[X] Windows Version (Unable to confirm if installed Windows version is 10 or greater)

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at C:\Users\faceb\AppData\Local\Android\sdk
    • Platform android-33-ext4, build-tools 33.0.1
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[!] Visual Studio - develop for Windows (Visual Studio Community 2022 17.5.3)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.5.33516.290
    X Visual Studio is missing necessary components. Please re-run the Visual Studio installer for the "Desktop development with C++" workload, and include these components:
        MSVC v142 - VS 2019 C++ x64/x86 build tools
         - If there are multiple build tool versions available, install the latest
        C++ CMake tools for Windows
        Windows 10 SDK

[√] Android Studio (version 2022.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[√] VS Code (version 1.76.2)
    • VS Code at C:\Users\faceb\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.60.0

[√] Connected device (4 available)
    • EML L09 (mobile)  • BPN0219301001602 • android-arm64  • Android 10 (API 29)
    • Windows (desktop) • windows          • windows-x64    • Microsoft Windows [Versione 10.0.19044.2846]
    • Chrome (web)      • chrome           • web-javascript • Google Chrome 113.0.5672.127
    • Edge (web)        • edge             • web-javascript • Microsoft Edge 113.0.1774.35

[√] HTTP Host Availability
    • All required HTTP hosts are available

**Comment by josemiguelvarela** [comment]
Hi, 

I don't know if the configuration is correct. Check the clientSecret and other fields, we are using something like this:

```
static final Config configB2Ca = Config(
      tenant: 'myTenant', //Without .onmicrosoft.com.
      clientId: 'f8a485e0-e8b8-4d98-b60d-acXXXXXXXXX',
      scope: 'f8a485e0-e8b8-4d98-b60d-acXXXXXXXXX offline_access',
      clientSecret: 'xxxxxxxxxx',
      isB2C: true,
      navigatorKey: navigatorKey,
      policy: 'b2c_1a_production_signin',
      tokenIdentifier: 'UNIQUE IDENTIFIER A',
      loader: SizedBox());
```

**Comment by emaborsa** [comment]
Ok, setting the tenant just the name and fixing the scope, I directly get `AadOauthFailure(ErrorType.AccessDeniedOrAuthenticationCanceled, Access denied or authentication canceled.)`. 
I do not have a client secret. Actually, I expected the browser gets opened where the user enters the credentials.

**Comment by CanadianN1nj4** [comment]
@emaborsa I believe you should have a client secret since it's required part of the AAD

**Comment by emaborsa** [comment]
@CanadianN1nj4 you write: 
> ...it's required part of the AAD

Do you mean for the Microsoft AAD or this library AAD? Because i am trying to access the B2C and for that the secret is not required, I have never used one since I am using B2C and the [Authorization Code Flow](https://learn.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-auth-code-flow).

**Comment by leobearth** [comment]
I'm having the same issue here. Was working fine until some days ago. My config:

```
Config(
      tenant: 'common',
      clientId: 'MY_CLIENT_ID',
      scope: scopes,
      redirectUri: 'msauth.${(appId)}://auth',
      navigatorKey: navigatorKey,
      loader: Center(child: CircularProgressIndicator()),
    );
```

Tried with the client secret (although it's not a good practice to keep client secrets in client code) and nothing changes. I'm getting the same `AadOauthFailure(ErrorType.AccessDeniedOrAuthenticationCanceled, Access denied or authentication canceled.)` error.

**Comment by LynxLynxx** [comment]
Somebody have solution for this?

**Comment by einatguri** [comment]
Has anyone found a solution or workaround for this ?
