### ISSUE TITLE
Macos/ios login error webview_flutter has not been set

### ISSUE THREAD

**Issue by DeltaFox0018** [Earlybyte/aad_oauth#242]
I installed the latest version (0.4.4) and using web login works without any problems

Instead when I try to do it via macos I get the following error: 
![Screenshot 2023-05-27 at 23 00 57](https://github.com/Earlybyte/aad_oauth/assets/35847603/60ca9f8a-bef9-4e31-afa6-0193ed050afd)

this is the configuration:

`
final Config configaad = Config(
  tenant: 'TENANT_ID',
  clientId: 'CLIENT_ID',
  scope: 'openid profile offline_access',
  navigatorKey: navigatorKey,
  loader: SizedBox(),
  redirectUri: "msauth.BUILD_IDENTIFIER://auth",
  webUseRedirect: false,
);
`

How can I solve the problem?

Do you have any sample code for macos/ios?

**Comment by DeltaFox0018** [comment]
The problem persists

**Comment by mikedigit** [comment]
If you pay close attention, the package is refered as Android/iOS and Web.
It lacks a proper mac implementation, and apparently defaults to the Mobile implementation and since Webview is not supported on MacOS(Android and iOS only) you have this problem.

**Comment by xeladu** [comment]
I get the same error and the current version on pub.dev shows support for Mac. So either this is a valid issue or the pub.dev page should be updated. Since 0.4.3, Mac is listed as a platform on pub.dev.
