### ISSUE TITLE
Msal Is Not Defined

### ISSUE THREAD

**Issue by LeeMatthewHiggins** [Earlybyte/aad_oauth#246]
Getting this issue on first access of the library. (Web version)
Was working fine, then started getting this 9 in 10 times (indicates not waiting for something to finish)
Msal Is Not Defined in the msalv2.js 47 (init function)

-tried changing the order of the scripts in index.html
-tired adding a delay to access the libaray

-investigated and found old issue: https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/950

Changed the msal-browser script index file to latest version, now *seems* to work. but since it was intermittent not 100% sure this is a fix.
  <script type="text/javascript" src="https://alcdn.msauth.net/browser/2.37.0/js/msal-browser.min.js" crossorigin="anonymous"></script></script>

<img width="938" alt="Screenshot 2023-06-21 at 09 35 23" src="https://github.com/Earlybyte/aad_oauth/assets/496316/44679d0e-7c4a-4ac8-b88b-7b259e28dc7b">

**Comment by LeeMatthewHiggins** [comment]
update: using the latest script seems to only have improved the odds. Very first time in its 9 in 10 times. After that it seems to work most of the time.

**Comment by loetsphi** [comment]
Create new issue if this is still relevant.
