### ISSUE TITLE
Login must be called again after login flow redirect back to web app

### ISSUE THREAD

**Issue by LeeMatthewHiggins** [Earlybyte/aad_oauth#247]
Redirection back to the web app after login success will reload the web app.
In this case hasCachedAccountInformation is false
Login must then be called again which will not invoke the web uI and will mean hasCachedAccountInformation is set to true. Awesome.
The problem is, you have no way of telling this. If you just call login at the start, then the web gui flow will be invoked if not logged in. This is not good UX and prevents having a landing or welcome page with a user activated login flow.
After login is called again, subsequent app reloads have  hasCachedAccountInformation set to true and works as expected.

Maybe there could be a isLoggedIn call that will refresh, but never start the web GUI.

Expected hasCachedAccountInformation is true after redirecting back from the web GUI flow.

Note, this happens if setting webUseRedirect to true in config, but not when using a pop up. Pop ups have issues on mobile browsers.

**Comment by LeeMatthewHiggins** [comment]
This gets me in a loop. :(
I have a work around, wait for 3 seconds before creating the AadOAuth- that seems to fix the issue when using web redirect on desktop web. 
However mobile web on iphone never navigates to the login in this mode!

**Comment by Freez** [comment]
I am struggling with the same problem, it would be nice if someone could create a working example...

**Comment by Freez** [comment]
@LeeMatthewHiggins 

I am still struggling, would you share your code?
