### ISSUE TITLE
Logout does not clear key from local storage/cache (android)

### ISSUE THREAD

**Issue by nicklohuis** [Earlybyte/aad_oauth#249]
the logout call doesn't clear the key, my app uses the availability of the key for authorization, so when i call logout and go back to the login page, it just authorizes immediately

**Comment by nayanAubie** [comment]
Same issue I have observed on Android and iOS as well.

**Comment by GDEVENDRAK** [comment]
> Same issue I have observed on Android and iOS as well. Also, trying to log out multiple times clears the key from local storage (generally after 2-3 tries)

@nayanAubie Hi, I also facing same issue for iOS logout which is working fine in Android. 

First time after opening the app, after `await mfaAuthentication.login();` calling `await mfaAuthentication.getAccessToken()` is not calling. 

After `mfaAuthentication.logout();` of application the second time below code is running. 

```
      await mfaAuthentication.login();
      String? accessToken = await mfaAuthentication.getAccessToken();
```

Please suggest if you resolve the issue.

**Comment by nayanbabariya** [comment]
@GDEVENDRAK `aad_oauth` is not using the native library for MSAL, instead, it is using a browser session and that is not a proper way for mobile. You can use this one if you like. (made by me) => [msal_auth](https://pub.dev/packages/msal_auth)

**Comment by AliGuemues** [comment]
I have the same issue on Flutter web. I have to log out twice that the cache is cleared properly.

I call the logout function and after that I clear the browser cache. Immediately after the logout, there are entries placed in the local storage that enables the direct login. After a second logout, these entries are deleted properly.

**Comment by GDEVENDRAK** [comment]
> @GDEVENDRAK `aad_oauth` is not using the native library for MSAL, instead, it is using a browser session and that is not a proper way for mobile. You can use this one if you like. (made by me) => [msal_auth](https://pub.dev/packages/msal_auth)

ok, I need to update to MSAL in future. Coming aad_oauth I noticed I am not calling `mfaAuthentication.logout();` in async. After adding async not it is working fine now. 

I will definitely check your package for MSAL. Thank you for the support.

**Comment by GDEVENDRAK** [comment]
> I have the same issue on Flutter web. I have to log out twice that the cache is cleared properly.
> 
> I call the logout function and after that I clear the browser cache. Immediately after the logout, there are entries placed in the local storage that enables the direct login. After a second logout, these entries are deleted properly.

Hi, I noticed I am not calling mfaAuthentication.logout(); in async. After adding async not it is working fine now.
