### ISSUE TITLE
loginHint doesn't work on web (but works on Andorid  & iOS)

### ISSUE THREAD

**Issue by KeeganDC** [Earlybyte/aad_oauth#250]
Using the same `Config` and `AadOAuth` object, I was get `config.loginHint` working on Android & iOS but it doesn't work from web
The login flow works on all 3 platforms (web using pop up flow) but the loginHint doesn't prepopulate on web

Maybe some discrepancy between `web_oauth.dart` and `mobile_oauth.dart`?

**Comment by joaovvrodrigues** [comment]
Same here :/

**Comment by joaovvrodrigues** [comment]
> found a potential workaround using `customParameters` though I'm not sure if this covers everything `loginHint` is used for
> 
> ```
>       Config(
>         ...
>         loginHint: email,
>         customParameters: {
>           // workaround for loginHint not working on web
>           if (kIsWeb && email?.isNotEmpty == true) 'login_hint': email ?? '',
>         },
>       );
> ```

@KeeganDC apparently it worked, thank you very much for your contribution.

**Comment by KeeganDC** [comment]
I haven't tested it but i assume #292 is the fix for this
