### ISSUE TITLE
Add support for Gov Cloud

### ISSUE THREAD

**Issue by defano** [Earlybyte/aad_oauth#254]
Great library—kudos to all who have contributed to this.

One apparent limitation: It cannot support gov cloud users (who must authenticate against a different domain than commercial users). Refer to the Azure AD [documentation here](https://learn.microsoft.com/en-us/azure/azure-government/documentation-government-aad-auth-qs#step-2--configure-your-app-to-use-your-azure-ad-tenant).

I would like to propose modifying the `Config` object so that the authorize and token URLs are configurable by:
* Adding named `String?` parameters: `authorizationUrl` and `tokenUrl`.
* Modify the constructor to assign the object properties these values when provided, or use the current logic when not. I.e., `this.authorizationUrl = authorizationUrl ?? isB2C ...`

I chose this approach rather than adding an `isGovCloud` flag since I suspect Microsoft may eventually offer other domains and endpoints for non-US private cloud users (if they don't already). This approach should provide the greatest flexibility for those that require it. 

I'd be happy to submit a PR if others agree with this approach.

**Comment by loetsphi** [comment]
@defano Is this limitation resolved (with 1.0.0) for your use case?

**Comment by defano** [comment]
I believe it is, but I haven't had a chance to fully test and confirm. I will close this ticket; worst case, I can re-open. 

Thanks for all the good work!
