### ISSUE TITLE
How to get Access Tokens for multiple resources

### ISSUE THREAD

**Issue by FBloembergen** [Earlybyte/aad_oauth#26]
Can I use this package for getting multiple access tokens?

Currently I'm faced with this situation:
- Get the 'default' scoped token for getting User.Read info from the Graph 
- Get a differently scoped token for getting data from my own WebAPI, for example 'api://{someID}/Data.Read'

I can get one or the other by setting up a single Config() like in the readme, but I'm not able to get both of the scopes when adding them together. This is not a great practice anyway, least privileged tokens for separate resources.

But 2 configurations with 2 instances of AadOAuth() won't give me separate access tokens. I think this has to do with how its cached/stored. (It will always grab the hardcoded 'Token')

Am I missing something or is this simply not yet supported?

**Comment by brunovsiqueira** [comment]
@FBloembergen did you solve your issue? Same problem here

**Comment by FBloembergen** [comment]
> @FBloembergen did you solve your issue? Same problem here

Closed the issue myself since I didnt need the solution anymore. Didnt solve it although it can be fixed by changing the hardcoded caching key.

**Comment by Matthew-Kanderka** [comment]
Do you mean the _tokenIdentifier_ field on the Config object? This seems to only work for B2C scenarios

**Comment by FBloembergen** [comment]
> Do you mean the _tokenIdentifier_ field on the Config object? This seems to only work for B2C scenarios

@Matthew-Kanderka I can only vaguely remember, but there used to be a cache key with the string literal `Token`. So no matter how many instances `AadOAuth` instances you created, you would always get the token it first cached. It didnt use any information from the `Config` to seperately cache the tokens.

It's been almost 5 years I created the issue so I can imagine things have changed. Sadly I don't have the time to go through the code.

**Comment by paulhwangfti** [comment]
@Matthew-Kanderka did you end up figuring it out?

**Comment by FBloembergen** [comment]
I havent tried it yet, but I do see you can now use a `tokenIdentifier` in the config. This wasnt there 4/5 years ago.
And you can use multiple configs, so I assume it would actually work now.

**Comment by paulhwangfti** [comment]
I wasn't aware that we were able to use multiple configs for a single `AadOauth` instance, where are you seeing that?

And this is the current way that I have it set up, although I'm running into issues where (I believe when the notificationsAuth access token is expired, it becomes null despite me also refreshing it)

```
static final Config config = Config(
    tenant: dotenv.env['MobileAppTenantId']!,
    clientId: dotenv.env['MobileAppClientId']!,
    scope: "${dotenv.env['AppScope']!} openid profile offline_access user.read",
    redirectUri: (Platform.isAndroid)
        ? dotenv.env['androidRedirectUri']!
        : dotenv.env['iOSRedirectUri'],
    navigatorKey: navigatorKey,
    // webUseRedirect: true, // default is false - on web only, forces a redirect flow instead of popup auth
    loader: const FtiLoadingScreen(),
    // postLogoutRedirectUri: 'http://your_base_url/logout', //optional
  );

  static final Config notificationConfig = Config(
    tenant: dotenv.env['MobileAppTenantId']!,
    clientId: dotenv.env['MobileAppClientId']!,
    scope: dotenv.env['NotificationAppScope']!,
    redirectUri: (Platform.isAndroid)
        ? dotenv.env['androidRedirectUri']!
        : dotenv.env['iOSRedirectUri'],
    navigatorKey: navigatorKey,
    tokenIdentifier: 'notificationToken',
    loader: const FtiLoadingScreen(),
  );

  final AadOAuth oauth = AadOAuth(config);
  final AadOAuth notificationAuth = AadOAuth(notificationConfig);
```
