### ISSUE TITLE
Hash Empty Error

### ISSUE THREAD

**Issue by Dannyisadog** [Earlybyte/aad_oauth#262]
Hi, I got the error below after finish aad authentication and it's not always happened
```
hash_empty_error: Hash value cannot be processed because it is empty. Please verify that your redirectUri is not clearing the hash. Given Url:  MY_REDIRECT_URI
```

<img width="581" alt="截圖 2023-09-06 下午12 01 11" src="https://github.com/Earlybyte/aad_oauth/assets/16824455/89b80fd8-bda0-4fb6-9386-2dc3647ca48f">

I had changed my redirect_uri to another page instead /login, reference to [docs](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/login-user.md#redirecturi-considerations)

**Comment by davor-layer-four** [comment]
@Dannyisadog  how did you solve this? I also started having this problem on flutter web.

**Comment by Dannyisadog** [comment]
Hi, @davor-layer-four 

I solved the problem is to create an empty page locate on /web/blank.html

Then, you should check the empty page could be access in browser

After that, set your AAD redirect uri to `http://localhost:8080/blank.html`.

I guess this problem is other pages will cache the hash value so you have to do that
