### ISSUE TITLE
http package version upgradation

### ISSUE THREAD

**Issue by domronak** [Earlybyte/aad_oauth#264]
Because aad_oauth >=0.4.4 depends on http ^0.13.6 and demo_sso depends on http ^1.1.0, aad_oauth >=0.4.4 is forbidden.
So, because demo_sso depends on aad_oauth ^0.4.4, version solving failed.

**Comment by Nonelela4980** [comment]
I also got the same issue

**Comment by tajjacob** [comment]
I already create pr for this issue #257
