### ISSUE TITLE
Http needs an upgrade

### ISSUE THREAD

**Issue by Nonelela4980** [Earlybyte/aad_oauth#265]
I got this error "Because aad_oauth >=0.4.4 depends on http ^0.13.6 and myapp depends on http ^1.1.0, aad_oauth >=0.4.4 is forbidden.
So, because myapp depends on aad_oauth ^0.4.4, version solving failed."

**Comment by Nonelela4980** [comment]
I ended up using dependency override and I was able to use the the newer version of http on my project. I'm not really sure it this is a good solution

**Comment by josemiguelvarela** [comment]
> I ended up using dependency override and I was able to use the the newer version of http on my project. I'm not really sure it this is a good solution

That's the solution we use. 
Anyway, we've already merge all the PRs and we'll have a new plugin version in the coming days.
