### ISSUE TITLE
Working example needed for web imlementation

### ISSUE THREAD

**Issue by Freez** [Earlybyte/aad_oauth#267]
I try to implement this package in our app but have a lot of issues. 

That's possible because I may have done something wrong myself, but I wonder whether the web implementation still works with the latest version of MSAL (2.35.0) and Flutter/Dart.

Does anyone have this working well in a web app? And has anyone managed to come up with a solution for the double login call?
Maybe someone could provide a working example because the existing example doesn't work.

**Comment by Freez** [comment]
@benbuf same here

I did receive a token in the web app, but the redirect does not work (yet). I'll try again later because I think it's possible to get this working.

**Comment by giuseppevega** [comment]
@Freez I have the same issue too.

**Comment by Freez** [comment]
@giuseppevega Yesterday I added the onGenerateRoute to check if the requested url contains a code parameter. In that case I send the app to a screen with an additional parameter to restart the login function. But it doesn't work, after redirection I got exceptions from msal.js

I'll try to get it working in a while because I really need it for this app.

**Comment by Freez** [comment]
Give it a try this morning, I managed to get the code from the redirect but I don't know how to get the acces token. Anyone who figure this out?

**Comment by Refaydeen** [comment]
same problem for me after authentication it is redirecting but can get a token and user details in mobile it is working ,is anyone found solutions please let me know

**Comment by tratum** [comment]
Did anyone get a solution to the web auth flow
