### ISSUE TITLE
Flutter Web support

### ISSUE THREAD

**Issue by sladomic** [Earlybyte/aad_oauth#27]

**Comment by Jeremywhiteley** [comment]
We really need a plug in like that that also supports Flutter web.

**Comment by buimanhhungit** [comment]
ME TO. Pls Support

**Comment by buimanhhungit** [comment]
ME TOO. Pls Support

**Comment by sladomic** [comment]
Current roadmap:
1. https://github.com/Earlybyte/aad_oauth/projects/2
2. https://github.com/Earlybyte/aad_oauth/projects/3

**Comment by AmbujaAK** [comment]
ME TOO. Pls Support
