### ISSUE TITLE
How to get refresh token 

### ISSUE THREAD

**Issue by Refaydeen** [Earlybyte/aad_oauth#271]
How to get refresh token ,can we do a sso in Microsoft through this  package,is that possible

**Comment by qaniel** [comment]
you can fetch it after a successful auth: 

``` dart
        final result = await authenticator.login(refreshIfAvailable: true);
        result.fold(
              (failure) => throw Exception(failure.message),
              (token) => token.refreshToken
        );
```

**Comment by Refaydeen** [comment]
the code above you mentioned will work on web also right?

**Comment by buechner** [comment]
Why do i need to call `login` to get the refresh token. In my opinion, it should be a different method. This way i can control whether the user will see the login screen or not.

**Comment by ariaguirre** [comment]
I'm having a similar issue where the authentication flow is only returning an object with the accessToken, and the refreshToken call is returning a 'null' value. I have already included the 'offline_access' scope in my request. Is there any update regarding this problem?

**Comment by AniketStemmOne** [comment]
@ariaguirre  have you got the solution i am facing same problem.

I am getting  null in refresh token always

**Comment by paulhwangfti** [comment]
> you can fetch it after a successful auth:
> 
> ```dart
>         final result = await authenticator.login(refreshIfAvailable: true);
>         result.fold(
>               (failure) => throw Exception(failure.message),
>               (token) => token.refreshToken
>         );
> ```

How does this differ from the built in function of `refreshToken()` ?

**Comment by srinivasii** [comment]
Hi any update on this?

**Comment by paulhwangfti** [comment]
> Hi any update on this?

Nope, haven't heard since but maybe looking into the codebase would answer that question. Just haven't gotten around to it yet.
