### ISSUE TITLE
Version solving failed.

### ISSUE THREAD

**Issue by SatishKumarRaizada** [Earlybyte/aad_oauth#273]
Because aad_oauth >=0.4.4 depends on http ^0.13.6 and copilot depends on http ^1.1.0, aad_oauth >=0.4.4 is forbidden.
So, because copilot depends on aad_oauth ^0.4.4, version solving failed.

I am not able to resolve the conflict here as i can not go back on older version for the http package.

**Comment by loetsphi** [comment]
solved with 1.0.0
