### ISSUE TITLE
Web force login

### ISSUE THREAD

**Issue by NeilPotot-Xam** [Earlybyte/aad_oauth#276]
Is there a way to do always show the login prompt in web?

I added `login` under prompt field but it just doesn't seem working.

I'm expecting that if `login` prompt is provided, it should force the login pop-up.

**Comment by LeoBound** [comment]
I have the same problem. I was expecting to be able to force the account selection screen with prompt=`select_account` but this didn't do anything and my web app logs straight into the previous account (even if I try and force a logout first).

The options are [here](https://learn.microsoft.com/en-us/entra/identity-platform/v2-oauth2-auth-code-flow).
