### ISSUE TITLE
unable to build app 

### ISSUE THREAD

**Issue by Shubham44-arya** [Earlybyte/aad_oauth#309]
Earlier it was working fine.

Since today getting the below error.

Error (Xcode): ../../.pub-cache/hosted/pub.dev/aad_oauth-1.0.1/lib/request_code.dart:60:17: Error: The method 'PopScope' isn't defined for the class 'RequestCode'.

Could not build the application for the simulator.
Error launching application on iPhone 15 Pro.

**Comment by rakeshtsasi** [comment]
I'm also facing this issue
