### ISSUE TITLE
Multi tenant and personal account.

### ISSUE THREAD

**Issue by rvbatista** [Earlybyte/aad_oauth#318]
To allow login of multi tenant and personal accounts it's necessary to use  a url without tenant id, otherwise we have error AADSTS50020
https://learn.microsoft.com/pt-br/troubleshoot/azure/entra/entra-id/app-integration/error-code-aadsts50020-user-account-identity-provider-does-not-exist

I tried to change my tenant id to common, but I believe that it's used in other parts of the code and still not working.

How it's the correct way to handle multi tenant and personal accounts?

**Comment by rvbatista** [comment]
after more tests change the tenant id to common worked.

**Comment by LynxLynxx** [comment]
Can you point where did you changed it to "common" @rvbatista

**Comment by rvbatista** [comment]
![Screenshot_2024-07-19-20-37-22-670_com.github.android.png](https://github.com/user-attachments/assets/2797bf5e-f50f-4485-bcf4-360e3e756d45)

In this tenant parameter of the config.
