### ISSUE TITLE
Any plans to add `select_account` to the list of available `prompt` values?

### ISSUE THREAD

**Issue by paulhwangfti** [Earlybyte/aad_oauth#330]
This is from `config.dart`
![image](https://github.com/user-attachments/assets/48330e80-685a-43d2-a0a4-58f696af5528)`

The full list of possible values that it _could_ be:
![image](https://github.com/user-attachments/assets/cd611e7d-2c73-497b-bf01-fde18abba160)
(link to above image here: https://learn.microsoft.com/en-us/entra/identity-platform/msal-js-prompt-behavior)

**Comment by loetsphi** [comment]
Hey @paulhwangfti 

The prompt values are not enforced by aad_oauth, have you tried to use the other values to see if they work?
This specific comment is already 4 years old. We can adjust or remove it.

**Comment by paulhwangfti** [comment]
Hi @loetsphi 

I tried with value `select_account` to no avail just now as the sign in page doesn't give me the option to select an account.
![image](https://github.com/user-attachments/assets/0611d118-cd3b-49c4-91b1-413f2a69e232)
![image](https://github.com/user-attachments/assets/cda8ec1f-5881-4347-bc45-9202390e1ac8)

**Comment by paulhwangfti** [comment]
@loetsphi also just gave `consent` prompt value a try and that seems to work as show below
![image](https://github.com/user-attachments/assets/78ce9733-87af-4190-a89d-6324035231f2)

**Comment by loetsphi** [comment]
![Screenshot 2024-08-05 at 15 40 00](https://github.com/user-attachments/assets/70ea3962-4cc5-4831-9d6e-15a20372147b)

'SELECT_ACCOUNT' works with Flutter Web. To allow the same behaviour for Android/iOs it probably needs some adjustment to RequestCode.dart to enable Cookies in the WebView...

**Comment by paulhwangfti** [comment]
@loetsphi looks like cookies are already enabled and, from a glance, they are only cleared when the user logs out. so i'm not 100% sure if that's the root of the issue...
![image](https://github.com/user-attachments/assets/3dba1b9c-01c5-4be1-a8d6-e1c6bd684dfc)

**Comment by paulhwangfti** [comment]
Scratch what I said, I was able to make some changes that seem to have enabled cookies and allowed for that `select_account` to work.
![image](https://github.com/user-attachments/assets/ad832409-d4ca-42b2-bc41-243e1cc35e27)
Going to create a PR for it right now
