### ISSUE TITLE
Can't use with Azure AD B2C

### ISSUE THREAD

**Issue by vitorbg2** [Earlybyte/aad_oauth#34]
I need to use aad_oauth with Azure AD B2C.
But, it isn't possible with that library, i am facing 2 problems in my journey to use B2C

1. I can't change the authorizationUrl
   Azure b2c requires another authorization Url, like: https://{Tenant}.b2clogin.com/{Tenant}..onmicrosoft.com/{flow}/oauth2/v2.0/authorize?
2. I can't use several flows
   With b2c i can create user flows, allowing my users to login with facebook, google, etc.. so I usually create a flow to company users and another one to external users, so i need to instantiate the class AadOauth two times inside my application (just to change my authorizationUrl), but, if i try to instantiate the class again, nothing happens.

   This problem occurs because that code don't change my first instance (because it isn't null anymore)
```dart
factory AadOAuth(config) {
    if ( AadOAuth._instance == null )
      AadOAuth._instance = new AadOAuth._internal(config);
    return _instance;
  }
```

**Comment by erickdaros** [comment]
I've been working on a B2C feature implementation to the aad_oauth library, i'm going to submit a PR for this issue

**Comment by vitorbg2** [comment]
Oh, thx bro. I really appreciate your work.

**Comment by raffzomp** [comment]
I'm sorry to pressure, but it would be great to get the PR #35 in asap @sladomic (if appropriate of course), as we are in the middle of reworking our app and this feature is right in time.

**Comment by Jeremywhiteley** [comment]
Will this work with Flutter web with Azure AD B2C?

**Comment by sladomic** [comment]
Hey @Jeremywhiteley I don't think it will work with Flutter web out of the box, since it uses https://pub.dev/packages/flutter_secure_storage and other plugins which don't have implementations for Flutter web so far
