### ISSUE TITLE
Separate Token with differents scope

### ISSUE THREAD

**Issue by Kabir-Giuralarocca** [Earlybyte/aad_oauth#351]
How can i obtain two separate token with different scope on Android? I tried with 2 different configuration to call 'getAccessToken' but i obtain the same token.

**Comment by justoke** [comment]
Not much detail to go on, I believe you would need two configurations. This would mean that you would have to authenticate, making two calls and get two tokens, one for each configuration. 

However, you can get one token for multiple scopes - this all depends on the app registration on your target directory. As the tokens might be used for secure storage - you have to manage which token stored and retrieved the values. This might be more complicated than intended with two configurations. I use one configuration and n number of scopes - one scope would be API access and another would be access as a user. 

```
final Config config1 = Config(
  azureTenantId: "YOUR_TENANT_ID",
  clientId: "YOUR_CLIENT_ID_1",
  scope: "scope1 scope2",
  redirectUri: "YOUR_REDIRECT_URI",
  tokenIdentifier: "token1",
);

final Config config2 = Config(
  azureTenantId: "YOUR_TENANT_ID",
  clientId: "YOUR_CLIENT_ID_2",
  scope: "scope3 scope4",
  redirectUri: "YOUR_REDIRECT_URI",
  tokenIdentifier: "token2",
);
```

**Comment by Kabir-Giuralarocca** [comment]
yes i have 2 configuration but when i call 'login' and  'getAccessToken' with the second configuration i obtain the token of the first config wich is of the first login i made. On web works fine, the problem is with Android

**Comment by justoke** [comment]
If you're using the same AadOAuth instance to get tokens for different scopes, without changing the tokenIdentifier, it might default to returning the same token. Thus, using separate instances with unique identifiers is crucial.

Assuming you have code similar to the below, the tokenIdentifier should be different still:

```
final AadOAuth oauthA = AadOAuth(configForScopeA);
final AadOAuth oauthB = AadOAuth(configForScopeB);

await oauthA.login();
String accessTokenA = await oauthA.getAccessToken();

await oauthB.login();
String accessTokenB = await oauthB.getAccessToken();
```
