### ISSUE TITLE
webview onUrlChanged exception not re-thrown.

### ISSUE THREAD

**Issue by paulpopiel** [Earlybyte/aad_oauth#37]
There is currently no way to catch the following error within `request_code.dart`:

`throw new Exception("Access denied or authentation canceled."); `

Putting in a test print statement in the calling function to test this:

```
Future<void> _performFullAuthFlow() async {
    String code;
    try {
      code = await _requestCode.requestCode();
      _token = await _requestToken.requestToken(code);
    } catch (e) {
      print('This is not caught');
      rethrow;
    }
  }
```

**Comment by Tharindu-Diluksha** [comment]
Hi all, Im having the same issue. It seems like the solution by @graknol would work. Any update?

**Comment by loetsphi** [comment]
Fix is merged
