### ISSUE TITLE
WebView UI is overlapping with status bar in Samsung galaxy s10+ mobile

### ISSUE THREAD

**Issue by yugandh** [Earlybyte/aad_oauth#4]
WebView UI is overlapping with status bar in Samsung galaxy s10+ mobile.
This issue on iOS works perfect, but on Android devices i am seeing grey bar on top.
Can you please see below attached screenshot

[IMG_0310.pdf](https://github.com/Earlybyte/aad_oauth/files/3075157/IMG_0310.pdf)

**Comment by tobiasmeier78** [comment]
Hi,

thank you for submitting a bug. Currently we are working on another project and unfortunately we don't have the time it usually takes to maintain such a library.

If you want to participate on the code we are open to discuss about it.

best regards

**Comment by yugandh** [comment]
created pull request to customize web view and will fix the above issue.
This pull request is exposing web view rect area to public and everyone can customize the web view area on screen and using platform check they can give different rect areas for iOS and Android.


https://github.com/Earlybyte/aad_oauth/pull/12
