### ISSUE TITLE
Release version 0.1.9

### ISSUE THREAD

**Issue by raffzomp** [Earlybyte/aad_oauth#41]
It would be great to get the latest (and important token & B2C) changes as an official 0.1.9 package release.

**Comment by Jeremywhiteley** [comment]
> It would be great to get the latest (and important token & B2C) changes as an official 0.1.9 package release.

I agree!   Yes please!

**Comment by sladomic** [comment]
Release is out. Sorry for the delay and thanks for the contribution!
