### ISSUE TITLE
Cannot catch return/cancel response on login 

### ISSUE THREAD

**Issue by luccaromaniello** [Earlybyte/aad_oauth#43]
Is there any way to catch the "Unhandled Exception: Exception: Access denied or authentation canceled" thrown by login method when the user taps on return and does not complete login after all?

I have tried to catch it by catchError method on Future, try catch clauses, and I had no success. I was wondering if you have any example available to catch this exception. Thanks.

**Comment by dominicorga3245** [comment]
I am also currently experiencing this issue. Any news on this one?

**Comment by luccaromaniello** [comment]
> 
> 
> I am also currently experiencing this issue. Any news on this one?

I had a login page with an animated button. So, what I tried to do to mask the issue was:
- Set a timer to loading state. If someone can sign in successfully, then nothing happens (this state resets on initState if user chooses to logout afterwards).
- If someone chooses to return and cancel sign in, the user has to wait for a couple seconds so that the button returns to its initial state.

Probably not the best way to handle this situation, but it worked for now.

**Comment by loetsphi** [comment]
solved with Release 0.2.0
