### ISSUE TITLE
Implement "Request an access token"

### ISSUE THREAD

**Issue by sladomic** [Earlybyte/aad_oauth#45]
https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-auth-code-flow#request-an-access-token

**Comment by rajeshtaneja** [comment]
Can you please help me, how I can get access code?
I am getting token_id but not access_code.

**Comment by sladomic** [comment]
the issue "request an access token" has been implemented already and it can be obtained using getAccessToken

**Comment by sladomic** [comment]
> Can you please help me, how I can get access code?
> I am getting token_id but not access_code.

I don't see any access_code in the documentation. Do you mean authorization_code? Please open a new issue if needed, since this one is already implemented
