### ISSUE TITLE
Token expires but still flagged as valid

### ISSUE THREAD

**Issue by sladomic** [Earlybyte/aad_oauth#5]
#### Description:
- Wait until the token has expired (typically 1 hour)
- Try to login

#### Expected Result:
- Token is expired and library fetches a new one with the refresh token

#### Actual Result:
- Token still flagged as valid, therefore the authentication fails afterwards

#### Additional Information
- The token is currently stored as a serialized json, which contains a key "expires_in" as the time in seconds, when the token expires. Now every time the token is loaded from storage/cache, the time is still the same and therefore the token will always be valid, although it has already expired.
- Fix by storing the actual timestamp, when the token will expire in UTC

**Comment by yugandh** [comment]
Hi @sladomic ,

I logged in to the mobile application(iOS and Android) using email and password.
After 1 hour i opened the app.
I used below code to make a Microsoft graph api call.

try {
await oauth.login();
String accessToken = await oauth.getAccessToken();
 var response = await http.get(https://graph.microsoft.com/v1.0/me/, headers: {"Authorization":  "Bearer  $accessToken});
      print(response.body);

    } catch (e) {
      print('login error');
    }
I am getting access token expiry error and unable to fetch data from Graph-API.(https://graph.microsoft.com/v1.0/me/)

I have used 0.1.6 version of this repository.
** can you please let me know,  is there any solution silently acquire access token without Sign-out the  application.**

**Comment by sladomic** [comment]
@yugandh with version 0.1.6 it should have been fixed, at least for my devices (Android & iOS) it works. Can you do a fresh install or try a logout (oauth.logout()) to force the removal of old tokens stored in Keystore / Keychain?

**Comment by yugandh** [comment]
Hi @sladomic,

After oauth.logout() it will work. But every time it will ask to enter user name and password to authenticate, after token expiry every 60 minutes.

Just know i pushed one commit in to the below branch, you can pull that branch give your microsoft credentials, it will fetch response for the first time and after 60 minutes it will give access token expiry error.

https://github.com/Earlybyte/aad_oauth/compare/master...yugandh:Test-Microsoft-Graph-API
