### ISSUE TITLE
Logout keeps the credentials stored on iOS

### ISSUE THREAD

**Issue by nikPast** [Earlybyte/aad_oauth#53]
Hello, when i logout on android and then login the behavior is correct and prompts me the login page. 
On iOS it keeps the user authenticated with last info without giving possibility to change account.

**Comment by sladomic** [comment]
We cannot reproduce this behaviour. Can you give us more information (device, OS version, etc.)

**Comment by funnygerman** [comment]
@sladomic I faced the same issue on Simulator. Maybe it's a simulator issued?!

However, I think, I can't reproduce it anymore too :(

**Comment by funnygerman** [comment]
@sladomic now I can describe steps to reproduce.

Device: Simulator iPhone 11 Pro (13.6)

1. Perform login (await oauth.login())

2. WebView will be opened

3. Enter your credentials

Finally you will see the following content in the WebView:

> Stayed signed in?
> Do this to reduce the number of times you are asked to sign in.
> 
> (Checkbox) Don't show again
> 
> No / Yes

4. Click "Yes"

5. Perform logout (await oauth.logout())

**Expected:**
if you perform login again, you need to enter your credentials again

**Given:**
The user is still logged in.

**Comment by fsantiago99** [comment]
I have same problem. Anyone has solved this?

**Comment by lhamycodes** [comment]
if you've not gotten a fix for this, I made one today.

kindly checkout https://github.com/lhamycodes/aad_oauth/tree/fix/bump-http

**Comment by nayanAubie** [comment]
Still the same issue with the latest version `aad_oauth: ^1.0.0`
Simulator `iOS  17.0`
