### ISSUE TITLE
tokenIsValid returns false

### ISSUE THREAD

**Issue by funnygerman** [Earlybyte/aad_oauth#57]
As mentioned above tokenIsValid() returns false before either login or getAccessToken was called.

I guess the solution would be either
1. the token should be loaded from the cache on init of the library
2. or on the first call of tokenIsValid
```  
Future<bool> tokenIsValid2() async {
    if (_token == null) {
      _token = await _authStorage.loadTokenToCache();
    }
    return Token.tokenIsValid(_token);
  }
```

**Comment by funnygerman** [comment]
It's still an issue, but no one from developers answer to it

**Comment by ariefsn** [comment]
Is this solve?
I've got this case too 🥺

**Comment by loetsphi** [comment]
hi there, sorry for not answering immediately
as you seem to have solved this issue, could you create a pull request and let us review it?

**Comment by funnygerman** [comment]
@loetsphi PR created
https://github.com/Earlybyte/aad_oauth/pull/70
