### ISSUE TITLE
Add configuration support for additional optional authorization url parameters

### ISSUE THREAD

**Issue by raffzomp** [Earlybyte/aad_oauth#61]
I've created a pull request to add support for additional optional auth url parameters. Such paremeters could be login_hint, domain_hint (for B2C), whr and others.

The config now exposes the "additionalAuthParameters" map which can be initially populated.

**Comment by loetsphi** [comment]
Thanks for the pull request, functionality is included in Release 0.2.0. (implementing parameters explicitly)
