### ISSUE TITLE
idToken is null

### ISSUE THREAD

**Issue by paurakhsharma** [Earlybyte/aad_oauth#63]
I am unable to get the `idToken` using `getIdToken()` but I am able to get the `accessToken` with `getAccessToken()`.

I am not sure what the problem is here. 

In application manifest.

`"oauth2AllowIdTokenImplicitFlow": true` is set.

Any kind of hint or suggestion would be highly appreciated.

Thank you.

**Comment by paurakhsharma** [comment]
Update: I am not using B2C directory, if that makes any difference.

**Comment by thye1997** [comment]
have you include the 'profile' in your scope?

**Comment by EffivityPK** [comment]
Do you have any updates regarding this?
