### ISSUE TITLE
AUD

### ISSUE THREAD

**Issue by nyaris** [Earlybyte/aad_oauth#64]
Hi guys, i have a problem that the token generated by lib aad_oauth, is different from the token generated by the backend.
The AUD property of the token, this is different, I wonder if there is a way to change that property?

**Comment by Galti** [comment]
With Xamarin Active Directory package you also set ```ResourceID``` and ```Authority``` properties. What are the properties for the mentioned ones?

I write this comment here as the received token's ```aud``` property is wrong.

**Comment by nyaris** [comment]
@Galti 
So, I need to generate more than one token for multiple resources in flutter using this lib aad_oauth, can you help me?
