### ISSUE TITLE
Expose Redirect URL property in config.dart file to public since if anyone wants to use different redirectURL then we need to make change inside oauth framework

### ISSUE THREAD

**Issue by yugandh** [Earlybyte/aad_oauth#7]
Expose Redirect URL property in config.dart file to public since if anyone wants to use different redirectURL then we need to make change inside oauth framework.

Actual:
this.redirectUri = "https://login.live.com/oauth20_desktop.srf"

Expected:
can you please expose above RedirectUri property to public and i can pass my own URL.

**Comment by tobiasmeier78** [comment]
Hi,

thank you for submitting a change request. Currently we are working on another project and unfortunately we don't have the time it usually takes to maintain such a library.

If you want to participate on the code we are open to discuss about it.

best regards

**Comment by yugandh** [comment]
Pull request created.
https://github.com/Earlybyte/aad_oauth/pull/9

**Comment by sladomic** [comment]
@yugandh thanks for the PR.
