### ISSUE TITLE
Azure AD B2C example configuration field

### ISSUE THREAD

**Issue by kangPrayit** [Earlybyte/aad_oauth#71]
I am trying to experiment with the Azure AD B2C Setup example.

Add your Azure tenant ID, tenantName, client ID (ID of App), client Secret (Secret of App) and redirectUrl in the main.dart source-code:

  static final Config configB2Ca = new Config(
      tenant: "YOUR_TENANT_NAME",
      clientId: "YOUR_CLIENT_ID",
      scope: "YOUR_CLIENT_ID offline_access",
      redirectUri: "https://login.live.com/oauth20_desktop.srf",
      clientSecret: "YOUR_CLIENT_SECRET",
      isB2C: true,
      policy: "YOUR_USER_FLOW___USER_FLOW_A",
      tokenIdentifier: "UNIQUE IDENTIFIER A");

I am struggling to fill the property in the field,
should it be tenant: "YOUR_TENANT_NAME" become tenantId?
how we can get scope, policy and tokenIdentifier.
could someone help me?

Thank You

**Comment by loonix** [comment]
Hi bro,

https://stageblablabla.onmicrosoft.com/....

XXXXXXXXXX will be your tenant name

maybe these links will help:
https://docs.microsoft.com/en-us/azure/databricks/security/secrets/secret-scopes
https://helpdesk.kaseya.com/hc/en-gb/articles/115002521251-How-Do-I-Find-My-Azure-AD-Tenant-Name-
