### ISSUE TITLE
Background color during loading of WebView

### ISSUE THREAD

**Issue by adgeg** [Earlybyte/aad_oauth#78]
Hy,

After looking to available methods, I don't find any way to change default white background colors of the webview while it is loading. Do you know how could I set it ? Or even better, if possible, to set an Image during the loading ?

Thanks a lot for your great job,
Gabriel

**Comment by loetsphi** [comment]
AAD_OAUTH just display the Azure AD login page using flutter_webview_plugin, Azure AD login cannot really be customized for mobile devices. To implement this feature there would be some kind of a man in the middle approach. If you can solve this feel free to submit a pull request.

**Comment by sladomic** [comment]
You can however add a company branding (background image, color, ...) in Azure portal AD settings https://docs.microsoft.com/en-us/azure/active-directory/fundamentals/customize-branding
