### ISSUE TITLE
Correct scope not returned in token

### ISSUE THREAD

**Issue by Damsjov** [Earlybyte/aad_oauth#79]
Hi, I'm new to Github so please bear with me if I don't post in the proper way.

I have implemented aad_oauth in order to sign users in to an app using Azure AD. I have configured the tenant according to specs and login works well. But when I try to retrieve the user profile by means of the access token I get the error 

'code': 'InvalidAuthenticationToken',
'message': 'CompactToken parsing failed with error code: 80049217',

When running the token through https://jwt.ms, scope is shown as this:

"scp": "openid profile email"

But my config looks like this:

  static final Config config = new Config(
      tenant: "[...]",
      clientId: "[...]",
      resource: "https://graph.microsoft.com/",
      scope: "https://graph.microsoft.com/user.read",
      redirectUri: "msauth://com.example.newsapp2/[...]"
    );

  final AadOAuth oauth = new AadOAuth(config);

The login function is taken directly from an exemplary post right here:

void login() async {
    try {
      await oauth.login();
      var accessToken = await oauth.getAccessToken();
      var response = await http.get(userProfileBaseUrl, headers: {authorization: bearer + accessToken});
      showMessage(response.body);
    } catch (e) {
      showError(e);
    }
}

What am I missing here?

Thanks, Claus

**Comment by diegodiaz22** [comment]
I believe you have to capitalize the Bearer in you header and leave a space:

var response = await http.get(userProfileBaseUrl, headers: {authorization: 'Bearer $accessToken'});

**Comment by Damsjov** [comment]
@diegodiaz22 Thanks, but in the header the 'bearer' is actually a variable with exactly that form: "Bearer ".
