### ISSUE TITLE
Offline Catcher

### ISSUE THREAD

**Issue by loonix** [Earlybyte/aad_oauth#82]
Hi guys,

I am facing a small issue with the plugin, in case the user forgets to turn on the internet connection is there any way you can return an error to the `oAuth.login();` so we have the option to show the user a message asking for them to connect?

**Comment by loonix** [comment]
I have made some changes and seems that I was able to get a catcher for offline mode, it works well on android but on ios it seems that it doesn't save the token so it asks me to login again with an internet connection

https://github.com/loonix/aad_oauth

**Comment by loonix** [comment]
Managed to sort my problem out, did some changes on the plugin to pass in the last token saved from the app cache, changes are in my previous link if anyone is interested. As this might not be required for everyone I will not do any PR for it.

**Comment by loetsphi** [comment]
Hey @loonix 
Thanks for the idea and execution.
Would it be possible for you to create a pull request, so we can review, merge and release it?

**Comment by loonix** [comment]
Sorry for taking a while to answer, between studying for exams and work, will try to make one PR soon.
