### ISSUE TITLE
ITMS-90809: Deprecated API Usage - UIWebView are no longer accepted

### ISSUE THREAD

**Issue by QuangAnh84** [Earlybyte/aad_oauth#83]
Hi all,

Currently I am using the latest version of our library.
When I upload the app to apple connect I got this issue:

ITMS-90809: Deprecated API Usage - New apps that use UIWebView are no longer accepted. Instead, use WKWebView for improved security and reliability. Learn more (https://developer.apple.com/documentation/uikit/uiwebview).

I saw that we are using flutter_webview_plugin, but they said that they used the WKWebView instead of UIWebView already.

Do someone have solution to solve this issue?

**Comment by matecode** [comment]
Any news on this ?

**Comment by loetsphi** [comment]
UIWebView update with #88
