### ISSUE TITLE
Not working on flutter web

### ISSUE THREAD

**Issue by asifsaifi92** [Earlybyte/aad_oauth#85]
I am using this package for authentication in mobile devices and its working fine but it's not working with flutter web . I am getting this error while working with web "Unsupported operation: Platform._operatingSystem"

**Comment by loetsphi** [comment]
not implemented mainly because flutter_secure_storage does not support web either.

**Comment by loetsphi** [comment]
@asifsaifi92 if you have an idea how to implement, we would always appreciate a pull request

**Comment by keinou** [comment]
Wouldn't it be possible to use localStorage for the web?
