### ISSUE TITLE
WebView is opening but never loads and stay blank

### ISSUE THREAD

**Issue by Valou1402** [Earlybyte/aad_oauth#90]
![image](https://user-images.githubusercontent.com/10058137/105501612-bbdb7800-5cc4-11eb-835b-fb8ec7811b78.png)

**Comment by loetsphi** [comment]
We need more information to reproduce the case.

- Did you adapt the config accordingly to the example? 
- Did you choose you choose additional settings?
- Can you try to activate stack trace and send us a possible output?
