### ISSUE TITLE
Refresh Token 

### ISSUE THREAD

**Issue by pim-wis** [Earlybyte/aad_oauth#92]
Hi,

Quick question: how do you implement the refresh token for the B2B auth flow?

I've integrated this package, but after 60 minutes the acces token expires and i get a 401 error. 

Thank you.

**Comment by pim-wis** [comment]
Nevermind, i see i'm using version 2.0.... I'll upgrade the package and try again.

**Comment by diegodiaz22** [comment]
Did that fix your error?
