### ISSUE TITLE
What's tokenIdentifier?

### ISSUE THREAD

**Issue by dreamflasher** [Earlybyte/aad_oauth#96]
I can't find the notion of a tokenIdentifier in the azure documentation: https://docs.microsoft.com/en-us/azure/active-directory-b2c/access-tokens

How does one obtain it?

**Comment by sladomic** [comment]
Hi Marcel, this is only the key for the internal secure storage. You only need it if you have multiple instances of this plugin (e. g. if you have multiple user flows in AD B2C).

**Comment by dreamflasher** [comment]
Thank you for the swift explanation @sladomic!
