### ISSUE TITLE
ad b2c: Public clients should not send a client_secret when redeeming a publicly acquired grant.

### ISSUE THREAD

**Issue by dreamflasher** [Earlybyte/aad_oauth#97]
Following your readme and code for a ad b2c login flow. There you suggest to add a client_secret, but according to this: https://stackoverflow.com/questions/49736910/client-secret-not-required-on-refresh-token-azure-b2c that's not needed in native apps (which flutter is). 

When I leave out the client_secret it's working without an error.

**Comment by jacojvv-dev** [comment]
I am also not specifying a client secret - and it works without error.

Furthermore the readme also specifies the following:

```dart
clientId: "YOUR_CLIENT_ID",
scope: "YOUR_CLIENT_ID offline_access",
```

Which isn't correct, as far as my use case goes. I have an actual scope in the scope field, e.g. "https://contoso.onmicrosoft.com/0b299746-8901-497b-80e4-44455472303e/api offline_access".

@dreamflasher could you confirm what you are using in the scope argument - I'll open a PR to update the readme if you are also using an actual scope and not just the client id.

**Comment by sladomic** [comment]
Hi both. Thanks for the input. @jacojvv-dev would you like to open a PR to update the README?

**Comment by ArveSystad** [comment]
For future readers who find this on top of their search hits:

This worked for me, with the exact same error message. Normal authorization flow, Azure AD B2C. ASP.NET Core 2.1:

```
.AddOpenIdConnect("MyScheme", options =>
                {
                    options.Authority = config.SignInAuthority;
                    options.ClientId = config.ClientId;
                    options.ClientSecret = config.ClientSecret;
                    options.ResponseType = "code id_token";
                    options.Scope.Clear();
                    options.Scope.Add("openid");
                    options.CallbackPath = "/LoginRedirectTarget";
                    options.Events.OnAuthorizationCodeReceived = context => { context.TokenEndpointRequest.ClientSecret = null; return Task.CompletedTask; };
                });
```

Notice the last line there, which removes the client secret from the outgoing request after AuthorizationCode is received.
